export const FREGUESIAS:{[municipio: string]:string[]} = {
  'Amarante': [
    "Ansiães",
    "Candemil",
    "Fregim",
    "Fridão",
    "Gondar",
    "Gouveia (São Simão)",
    "Jazente",
    "Lomba",
    "Louredo",
    "Lufrei",
    "Mancelos",
    "Padronelo",
    "Rebordelo",
    "Salvador do Monte",
    "Telões",
    "Travanca",
    "União das freguesias de Aboadela, Sanche e Várzea",
    "União das freguesias de Amarante (São Gonçalo), Madalena, Cepelos e Gatão",
    "União das freguesias de Bustelo, Carneiro e Carvalho de Rei",
    "União das freguesias de Figueiró (Santiago e Santa Cristina)",
    "União das freguesias de Freixo de Cima e de Baixo",
    "União das freguesias de Olo e Canadelo",
    "União das freguesias de Vila Garcia, Aboim e Chapa",
    "Vila Caiz",
    "Vila Chã do Marão",
    "Vila Meã",
  ],
  'Baião': [
    "Frende",
    "Gestaçô",
    "Gove",
    "Grilo",
    "Loivos do Monte",
    "Santa Marinha do Zêzere",
    "União das freguesias de Ancede e Ribadouro",
    "União das freguesias de Baião (Santa Leocádia) e Mesquinhata",
    "União das freguesias de Campelo e Ovil",
    "União das freguesias de Loivos da Ribeira e Tresouras",
    "União das freguesias de Santa Cruz do Douro e São Tomé de Covelas",
    "União das freguesias de Teixeira e Teixeiró",
    "Valadares",
    "Viariz",
  ],
  'Castelo de Paiva': [
    "Bairros",
    "Fornos",
    "Paraíso",
    "Pedorido",
    "Raiva",
    "Real",
    "Santa Maria de Sardoura",
    "Sobrado",
    "São Martinho de Sardoura",
  ],
  'Celorico de Basto': [
    "Agilde",
    "Arnóia",
    "Basto (São Clemente)",
    "Borba de Montanha",
    "Codeçoso",
    "Fervença",
    "Moreira do Castelo",
    "Rego",
    "Ribas",
    "União das freguesias de Britelo, Gémeos e Ourilhe",
    "União das freguesias de Canedo de Basto e Corgo",
    "União das freguesias de Carvalho e Basto (Santa Tecla)",
    "União das freguesias de Caçarilhe e Infesta",
    "União das freguesias de Veade, Gagos e Molares",
    "Vale de Bouro",
  ],
  'Cinfães': [
    "Cinfães",
    "Espadanedo",
    "Ferreiros de Tendais",
    "Fornelos",
    "Moimenta",
    "Nespereira",
    "Oliveira do Douro",
    "Santiago de Piães",
    "Souselo",
    "São Cristóvão de Nogueira",
    "Tarouquela",
    "Tendais",
    "Travanca",
    "União das freguesias de Alhões, Bustelo, Gralheira e Ramires",
  ],
  'Felgueiras': [
    "Airães",
    "Aião",
    "Friande",
    "Idães",
    "Jugueiros",
    "Penacova",
    "Pinheiro",
    "Pombeiro de Ribavizela",
    "Refontoura",
    "Regilde",
    "Revinhade",
    "Sendim",
    "União das freguesias de Macieira da Lixa e Caramos",
    "União das freguesias de Margaride (Santa Eulália), Várzea, Lagares, Varziela e Moure",
    "União das freguesias de Pedreira, Rande e Sernande",
    "União das freguesias de Torrados e Sousa",
    "União das freguesias de Unhão e Lordelo",
    "União das freguesias de Vila Cova da Lixa e Borba de Godim",
    "União das freguesias de Vila Fria e Vizela (São Jorge)",
    "União das freguesias de Vila Verde e Santão",
  ],
  'Lousada': [
    "Aveleda",
    "Barrosas (Santo Estêvão)",
    "Caíde de Rei",
    "Lodares",
    "Lustosa",
    "Macieira",
    "Meinedo",
    "Nevogilde",
    "Sousela",
    "Torno",
    "União das freguesias de Cernadelo e Lousada (São Miguel e Santa Margarida)",
    "União das freguesias de Cristelos, Boim e Ordem",
    "União das freguesias de Figueiras e Covas",
    "União das freguesias de Nespereira e Casais",
    "União das freguesias de Silvares, Pias, Nogueira e Alvarenga",
    "Vilar do Torno e Alentém",
  ],
  'Marco de Canaveses': [
    "Alpendorada, Várzea e Torrão",
    "Avessadas e Rosém",
    "Banho e Carvalhosa",
    "Bem Viver",
    "Constance",
    "Marco",
    "Paredes de Viadores e Manhuncelos",
    "Paços de Gaiolo",
    "Penha Longa",
    "Sande e São Lourenço do Douro",
    "Santo Isidoro e Livração",
    "Soalhães",
    "Sobretâmega",
    "Tabuado",
    "Vila Boa de Quires e Maureles",
    "Vila Boa do Bispo",
    "Várzea, Aliviada e Folhada",
  ],
  'Paços de Ferreira': [
    "Arreigada",
    "Carvalhosa",
    "Codessos",
    "Eiriz",
    "Ferreira",
    "Figueiró",
    "Frazão",
    "Freamunde",
    "Lamoso",
    "Meixomil",
    "Modelos",
    "Paços de Ferreira",
    "Penamaior",
    "Raimonda",
    "Sanfins de Ferreira",
    "Seroa",
  ],
  'Penafiel': [
    "Abragão",
    "Boelhe",
    "Bustelo",
    "Cabeça Santa",
    "Canelas",
    "Capela",
    "Castelões",
    "Croca",
    "Duas Igrejas",
    "Eja",
    "Fonte Arcada",
    "Galegos",
    "Guilhufe e Urrô",
    "Irivo",
    "Lagares e Figueira",
    "Luzim e Vila Cova",
    "Oldrões",
    "Paço de Sousa",
    "Penafiel",
    "Perozelo",
    "Rans",
    "Recezinhos (São Mamede)",
    "Recezinhos (São Martinho)",
    "Rio Mau",
    "Rio de Moinhos",
    "Sebolido",
    "Termas de São Vicente",
    "Valpedre",
  ],
  'Resende': [
    "Barrô",
    "Cárquere",
    "Paus",
    "Resende",
    "São Cipriano",
    "São João de Fontoura",
    "São Martinho de Mouros",
    "União das freguesias de Anreade e São Romão de Aregos",
    "União das freguesias de Felgueiras e Feirão",
    "União das freguesias de Freigil e Miomães",
    "União das freguesias de Ovadas e Panchorra",
  ],
  'Torres Vedras': [
    "A dos Cunhados",
    "Dois Portos",
    "Freiria",
    "Maceira",
    "Ponte do Rol",
    "Ramalhal",
    "Runa",
    "Santa Maria, São Pedro e Matacães",
    "Silveira",
    "São Pedro da Cadeira",
    "Turcifal",
    "União das freguesias de Campelos e Outeiro da Cabeça",
    "União das freguesias de Carvoeira e Carmões",
    "União das freguesias de Maxial e Monte Redondo",
    "Ventosa",
  ],
  'Caldas da Rainha': [
    "A dos Francos",
    "Alvorninha",
    "Carvalhal Benfeito",
    "Foz do Arelho",
    "Landal",
    "Nadadouro",
    "Salir de Matos",
    "Santa Catarina",
    "União das freguesias de Caldas da Rainha - Nossa Senhora do Pópulo, Coto e São Gregório",
    "União das freguesias de Caldas da Rainha - Santo Onofre e Serra do Bouro",
    "União das freguesias de Tornada e Salir do Porto",
    "Vidais",
  ],
  'Óbidos': [
    "A dos Negros",
    "Amoreira",
    "Gaeiras",
    "Olho Marinho",
    "Santa Maria, São Pedro e Sobral da Lagoa",
    "Usseira",
    "Vau",
  ],
  'Barcelos': [
    "Abade de Neiva",
    "Aborim",
    "Adães",
    "Airó",
    "Aldreu",
    "Alvelos",
    "Arcozelo",
    "Areias",
    "Balugães",
    "Barcelinhos",
    "Barcelos",
    "Barqueiros",
    "Cambeses",
    "Carapeços",
    "Carvalhal",
    "Carvalhas",
    "Cossourado",
    "Cristelo",
    "Fornelos",
    "Fragoso",
    "Galegos (Santa Maria)",
    "Galegos (São Martinho)",
    "Gilmonde",
    "Lama",
    "Lijó",
    "Macieira de Rates",
    "Manhente",
    "Martim",
    "Moure",
    "Oliveira",
    "Palme",
    "Panque",
    "Paradela",
    "Pereira",
    "Perelhal",
    "Pousa",
    "Remelhe",
    "Rio Covo (Santa Eugénia)",
    "Rio Covo (Santa Eulália)",
    "Roriz",
    "Silva",
    "Silveiros",
    "Tamel (São Veríssimo)",
    "Ucha",
    "União das freguesias de Alheira e Igreja Nova",
    "União das freguesias de Alvito (São Pedro e São Martinho) e Couto",
    "União das freguesias de Areias de Vilar e Encourados",
    "União das freguesias de Campo e Tamel (São Pedro Fins)",
    "União das freguesias de Carreira e Fonte Coberta",
    "União das freguesias de Chorente, Góios, Courel, Pedra Furada e Gueral",
    "União das freguesias de Creixomil e Mariz",
    "União das freguesias de Durrães e Tregosa",
    "União das freguesias de Gamil e Midões",
    "União das freguesias de Milhazes, Vilar de Figos e Faria",
    "União das freguesias de Negreiros e Chavão",
    "União das freguesias de Quintiães e Aguiar",
    "União das freguesias de Sequeade e Bastuço (São João e Santo Estevão)",
    "União das freguesias de Tamel (Santa Leocádia) e Vilar do Monte",
    "União das freguesias de Viatodos, Grimancelos, Minhotães e Monte de Fralães",
    "União das freguesias de Vila Cova e Feitos",
    "Vila Boa",
    "Vila Frescainha (São Martinho)",
    "Vila Frescainha (São Pedro)",
    "Vila Seca",
    "Várzea",
  ],
  'Cabeceiras de Basto': [
    "Abadim",
    "Basto",
    "Bucos",
    "Cabeceiras de Basto",
    "Cavez",
    "Faia",
    "Outeiro",
    "Painzela",
    "Pedraça",
    "Refojos de Basto",
    "Rio Douro",
    "União das freguesias de Alvite e Passos",
    "União das freguesias de Arco de Baúlhe e Vila Nune",
    "União das freguesias de Gondiães e Vilar de Cunhas",
  ],
  'Mirandela': [
    "Abambres",
    "Abreiro",
    "Aguieiras",
    "Alvites",
    "Bouça",
    "Cabanelas",
    "Caravelas",
    "Carvalhais",
    "Cedães",
    "Cobro",
    "Fradizela",
    "Frechas",
    "Lamas de Orelhão",
    "Mascarenhas",
    "Mirandela",
    "Múrias",
    "Passos",
    "Suçães",
    "São Pedro Velho",
    "São Salvador",
    "Torre de Dona Chama",
    "União das freguesias de Avantos e Romeu",
    "União das freguesias de Avidagos, Navalho e Pereira",
    "União das freguesias de Barcel, Marmelos e Valverde da Gestosa",
    "União das freguesias de Franco e Vila Boa",
    "União das freguesias de Freixeda e Vila Verde",
    "Vale de Asnes",
    "Vale de Gouvinhas",
    "Vale de Salgueiro",
    "Vale de Telhas",
  ],
  'Vila Real': [
    "Abaças",
    "Andrães",
    "Arroios",
    "Campeã",
    "Folhadela",
    "Guiães",
    "Lordelo",
    "Mateus",
    "Mondrões",
    "Parada de Cunhos",
    "Torgueda",
    "União das freguesias de Adoufe e Vilarinho de Samardã",
    "União das freguesias de Borbela e Lamas de Olo",
    "União das freguesias de Constantim e Vale de Nogueiras",
    "União das freguesias de Mouçós e Lamares",
    "União das freguesias de Nogueira e Ermida",
    "União das freguesias de Pena, Quintã e Vila Cova",
    "União das freguesias de São Tomé do Castelo e Justes",
    "Vila Marim",
    "Vila Real",
  ],
  'Monção': [
    "Abedim",
    "Barbeita",
    "Barroças e Taias",
    "Bela",
    "Cambeses",
    "Lara",
    "Longos Vales",
    "Merufe",
    "Moreira",
    "Pias",
    "Pinheiros",
    "Podame",
    "Portela",
    "Riba de Mouro",
    "Segude",
    "Tangil",
    "Trute",
    "União das freguesias de Anhões e Luzio",
    "União das freguesias de Ceivães e Badim",
    "União das freguesias de Mazedo e Cortes",
    "União das freguesias de Messegães, Valadares e Sá",
    "União das freguesias de Monção e Troviscoso",
    "União das freguesias de Sago, Lordelo e Parada",
    "União das freguesias de Troporiz e Lapela",
  ],
  'Santiago do Cacém': [
    "Abela",
    "Alvalade",
    "Cercal",
    "Ermidas-Sado",
    "Santo André",
    "São Domingos",
    "São Francisco da Serra",
    "União das freguesias de Santiago do Cacém, Santa Cruz e São Bartolomeu da Serra",
    "Vale de Água",
  ],
  'Santarém': [
    "Abitureiras",
    "Abrã",
    "Alcanede",
    "Alcanhões",
    "Almoster",
    "Amiais de Baixo",
    "Arneiro das Milhariças",
    "Gançaria",
    "Moçarria",
    "Pernes",
    "Póvoa da Isenta",
    "São Vicente do Paul",
    "União das freguesias de Achete, Azoia de Baixo e Póvoa de Santarém",
    "União das freguesias de Azoia de Cima e Tremês",
    "União das freguesias de Casével e Vaqueiros",
    "União das freguesias de Romeira e Várzea",
    "União de freguesias da cidade de Santarém",
    "Vale de Figueira",
    "Vale de Santarém",
  ],
  'Pombal': [
    "Abiul",
    "Albergaria dos Doze",
    "Almagreira",
    "Carnide",
    "Carriço",
    "Guia",
    "Ilha",
    "Louriçal",
    "Mata Mourisca",
    "Meirinhas",
    "Pelariga",
    "Pombal",
    "Redinha",
    "Santiago de Litém",
    "São Simão de Litém",
    "Vermoil",
    "Vila Cã",
  ],
  'Vila Verde': [
    "Aboim da Nóbrega e Gondomar",
    "Atiães",
    "Cabanelas",
    "Cervães",
    "Coucieiro",
    "Dossãos",
    "Freiriz",
    "Gême",
    "Lage",
    "Lanhas",
    "Loureira",
    "Moure",
    "Oleiros",
    "Parada de Gatim",
    "Pico",
    "Ponte",
    "Prado (São Miguel)",
    "Sabariz",
    "Soutelo",
    "Turiz",
    "União das freguesias da Ribeira do Neiva",
    "União das freguesias de Carreiras (São Miguel) e Carreiras (Santiago)",
    "União das freguesias de Escariz (São Mamede) e Escariz (São Martinho)",
    "União das freguesias de Esqueiros, Nevogilde e Travassós",
    "União das freguesias de Marrancos e Arcozelo",
    "União das freguesias de Oriz (Santa Marinha) e Oriz (São Miguel)",
    "União das freguesias de Pico de Regalados, Gondiães e Mós",
    "União das freguesias de Sande, Vilarinho, Barros e Gomide",
    "União das freguesias de Valbom (São Pedro), Passô e Valbom (São Martinho)",
    "União das freguesias do Vade",
    "Valdreu",
    "Vila Verde e Barbudo",
    "Vila de Prado",
  ],
  'Arcos de Valdevez': [
    "Aboim das Choças",
    "Aguiã",
    "Cabana Maior",
    "Cabreiro",
    "Cendufe",
    "Couto",
    "Gavieira",
    "Gondoriz",
    "Jolda (São Paio)",
    "Miranda",
    "Monte Redondo",
    "Oliveira",
    "Padroso",
    "Paçô",
    "Prozelo",
    "Rio Frio",
    "Rio de Moinhos",
    "Sabadim",
    "Senharei",
    "Sistelo",
    "Soajo",
    "União das freguesias de Alvora e Loureda",
    "União das freguesias de Arcos de Valdevez (Salvador), Vila Fonche e Parada",
    "União das freguesias de Arcos de Valdevez (São Paio) e Giela",
    "União das freguesias de Eiras e Mei",
    "União das freguesias de Grade e Carralcova",
    "União das freguesias de Guilhadeses e Santar",
    "União das freguesias de Jolda (Madalena) e Rio Cabrão",
    "União das freguesias de Padreiro (Salvador e Santa Cristina)",
    "União das freguesias de Portela e Extremo",
    "União das freguesias de Souto e Tabaçô",
    "União das freguesias de São Jorge e Ermelo",
    "União das freguesias de Távora (Santa Maria e São Vicente)",
    "União das freguesias de Vilela, São Cosme e São Damião e Sá",
    "Vale",
    "Ázere",
  ],
  'Viseu': [
    "Abraveses",
    "Bodiosa",
    "Calde",
    "Campo",
    "Cavernães",
    "Cota",
    "Coutos de Viseu",
    "Fragosela",
    "Freguesia de Fail e Vila Chã de Sá",
    "Lordosa",
    "Mundão",
    "Orgens",
    "Povolide",
    "Ranhados",
    "Repeses e São Salvador",
    "Ribafeita",
    "Rio de Loba",
    "Santos Evos",
    "Silgueiros",
    "São Cipriano e Vil de Souto",
    "São João de Lourosa",
    "São Pedro de France",
    "União das freguesias de Barreiros e Cepões",
    "União das freguesias de Boa Aldeia, Farminhão e Torredeita",
    "Viseu",
  ],
  'Mangualde': [
    "Abrunhosa-a-Velha",
    "Alcafache",
    "Cunha Baixa",
    "Espinho",
    "Fornos de Maceira Dão",
    "Freixiosa",
    "Quintela de Azurara",
    "São João da Fresta",
    "União das freguesias de Mangualde, Mesquitela e Cunha Alta",
    "União das freguesias de Moimenta de Maceira Dão e Lobelhe do Mato",
    "União das freguesias de Santiago de Cassurrães e Póvoa de Cervães",
    "União das freguesias de Tavares (Chãs, Várzea e Travanca)",
  ],
  'Nordeste': [
    "Achada",
    "Achadinha",
    "Algarvia",
    "Lomba da Fazenda",
    "Nordeste",
    "Salga",
    "Santana",
    "Santo António de Nordestinho",
    "São Pedro de Nordestinho",
  ],
  'Porto Moniz': [
    "Achadas da Cruz",
    "Porto Moniz",
    "Ribeira da Janela",
    "Seixal",
  ],
  'Braga': [
    "Adaúfe",
    "Braga (São Vicente)",
    "Braga (São Vítor)",
    "Espinho",
    "Esporões",
    "Figueiredo",
    "Gualtar",
    "Lamas",
    "Mire de Tibães",
    "Padim da Graça",
    "Palmeira",
    "Pedralva",
    "Priscos",
    "Ruilhe",
    "Sequeira",
    "Sobreposta",
    "Tadim",
    "Tebosa",
    "União das freguesias de Arentim e Cunha",
    "União das freguesias de Braga (Maximinos, Sé e Cividade)",
    "União das freguesias de Braga (São José de São Lázaro e São João do Souto)",
    "União das freguesias de Cabreiros e Passos (São Julião)",
    "União das freguesias de Celeirós, Aveleda e Vimieiro",
    "União das freguesias de Crespos e Pousada",
    "União das freguesias de Escudeiros e Penso (Santo Estêvão e São Vicente)",
    "União das freguesias de Este (São Pedro e São Mamede)",
    "União das freguesias de Ferreiros e Gondizalves",
    "União das freguesias de Guisande e Oliveira (São Pedro)",
    "União das freguesias de Lomar e Arcos",
    "União das freguesias de Merelim (São Paio), Panoias e Parada de Tibães",
    "União das freguesias de Merelim (São Pedro) e Frossos",
    "União das freguesias de Morreira e Trandeiras",
    "União das freguesias de Nogueira, Fraião e Lamaçães",
    "União das freguesias de Nogueiró e Tenões",
    "União das freguesias de Real, Dume e Semelhe",
    "União das freguesias de Santa Lucrécia de Algeriz e Navarra",
    "União das freguesias de Vilaça e Fradelos",
  ],
  'Tabuaço': [
    "Adorigo",
    "Arcos",
    "Chavães",
    "Desejosa",
    "Granja do Tedo",
    "Longa",
    "Sendim",
    "Tabuaço",
    "União das freguesias de Barcos e Santa Leocádia",
    "União das freguesias de Paradela e Granjinha",
    "União das freguesias de Pinheiros e Vale de Figueira",
    "União das freguesias de Távora e Pereiro",
    "Valença do Douro",
  ],
  'Guarda': [
    "Adão",
    "Aldeia Viçosa",
    "Aldeia do Bispo",
    "Alvendre",
    "Arrifana",
    "Avelãs da Ribeira",
    "Benespera",
    "Casal de Cinza",
    "Castanheira",
    "Cavadoude",
    "Codesseiro",
    "Faia",
    "Famalicão",
    "Fernão Joanes",
    "Gonçalo",
    "Gonçalo Bocas",
    "Guarda",
    "Jarmelo São Miguel",
    "Jarmelo São Pedro",
    "João Antão",
    "Marmeleiro",
    "Maçainhas",
    "Meios",
    "Panoias de Cima",
    "Pega",
    "Porto da Carne",
    "Pêra do Moço",
    "Ramela",
    "Santana da Azinha",
    "Sobral da Serra",
    "União de freguesias de Avelãs de Ambom e Rocamondo",
    "União de freguesias de Corujeira e Trinta",
    "União de freguesias de Mizarela, Pêro Soares e Vila Soeiro",
    "União de freguesias de Pousade e Albardo",
    "União de freguesias de Rochoso e Monte Margarida",
    "Vale de Estrela",
    "Valhelhas",
    "Vela",
    "Videmonte",
    "Vila Cortês do Mondego",
    "Vila Fernando",
    "Vila Franca do Deão",
    "Vila Garcia",
  ],
  'Viana do Castelo': [
    "Afife",
    "Alvarães",
    "Amonde",
    "Anha",
    "Areosa",
    "Barroselas",
    "Cardielos",
    "Carreço",
    "Carvoeiro",
    "Castelo do Neiva",
    "Chafé",
    "Darque",
    "Freixieiro de Soutelo",
    "Lanheses",
    "Mazarefes",
    "Montaria",
    "Mujães",
    "Outeiro",
    "Perre",
    "Santa Marta de Portuzelo",
    "Serreleis",
    "São Romão de Neiva",
    "União das freguesias de Geraz do Lima (Santa Maria, Santa Leocádia e Moreira) e Deão",
    "União das freguesias de Nogueira, Meixedo e Vilar de Murteda",
    "União das freguesias de Subportela, Deocriste e Portela Susã",
    "União das freguesias de Torre e Vila Mou",
    "União das freguesias de Viana do Castelo (Santa Maria Maior e Monserrate) e Meadela",
    "Vila Franca",
    "Vila Fria",
    "Vila de Punhe",
  ],
  'Águeda': [
    "Agadão",
    "Aguada de Baixo",
    "Aguada de Cima",
    "Barrô",
    "Belazaima do Chão",
    "Borralha",
    "Castanheira do Vouga",
    "Fermentelos",
    "Macinhata do Vouga",
    "União das freguesias de Recardães e Espinhel",
    "União das freguesias de Travassô e Óis da Ribeira",
    "União das freguesias de Trofa, Segadães e Lamas do Vouga",
    "União das freguesias do Préstimo e Macieira de Alcoba",
    "Valongo do Vouga",
    "Águeda",
  ],
  'Pinhel': [
    "Agregação das freguesias Sul de Pinhel",
    "Alto do Palurdo",
    "Alverca da Beira/Bouça Cova",
    "Ervedosa",
    "Freixedas",
    "Lamegal",
    "Lameiras",
    "Manigoto",
    "Pala",
    "Pinhel",
    "Pínzio",
    "Souro Pires",
    "Terras de Massueime",
    "União das freguesias de Atalaia e Safurdão",
    "Valbom/Bogalhal",
    "Vale do Côa",
    "Vale do Massueime",
    "Vascoveiro",
  ],
  'Santo Tirso': [
    "Agrela",
    "Aves",
    "Monte Córdova",
    "Negrelos (São Tomé)",
    "Rebordões",
    "Reguenga",
    "Roriz",
    "União das freguesias de Areias, Sequeiró, Lama e Palmeira",
    "União das freguesias de Carreira e Refojos de Riba de Ave",
    "União das freguesias de Lamelas e Guimarei",
    "União das freguesias de Santo Tirso, Couto (Santa Cristina e São Miguel) e Burgães",
    "Vila Nova do Campo",
    "Vilarinho",
    "Água Longa",
  ],
  'Vinhais': [
    "Agrochão",
    "Candedo",
    "Celas",
    "Edral",
    "Edrosa",
    "Ervedosa",
    "Paçó",
    "Penhas Juntas",
    "Rebordelo",
    "Santalha",
    "Tuizelo",
    "União das freguesias de Curopos e Vale de Janeiro",
    "União das freguesias de Moimenta e Montouto",
    "União das freguesias de Nunes e Ousilhão",
    "União das freguesias de Quirás e Pinheiro Novo",
    "União das freguesias de Sobreiro de Baixo e Alvaredos",
    "União das freguesias de Soeira, Fresulfe e Mofreita",
    "União das freguesias de Travanca e Santa Cruz",
    "União das freguesias de Vilar de Lomba e São Jomil",
    "Vale das Fontes",
    "Vila Boa de Ousilhão",
    "Vila Verde",
    "Vilar Seco de Lomba",
    "Vilar de Ossos",
    "Vilar de Peregrinos",
    "Vinhais",
  ],
  'Paredes de Coura': [
    "Agualonga",
    "Castanheira",
    "Coura",
    "Cunha",
    "Infesta",
    "Mozelos",
    "Padornelo",
    "Parada",
    "Romarigães",
    "Rubiães",
    "União das freguesias de Bico e Cristelo",
    "União das freguesias de Cossourado e Linhares",
    "União das freguesias de Formariz e Ferreira",
    "União das freguesias de Insalde e Porreiras",
    "União das freguesias de Paredes de Coura e Resende",
    "Vascões",
  ],
  'Praia da Vitória': [
    "Agualva",
    "Biscoitos",
    "Cabo da Praia",
    "Fonte do Bastardo",
    "Fontinhas",
    "Lajes",
    "Porto Martins",
    "Praia da Vitória (Santa Cruz)",
    "Quatro Ribeiras",
    "São Brás",
    "Vila Nova",
  ],
  'Figueiró dos Vinhos': [
    "Aguda",
    "Arega",
    "Campelo",
    "União das freguesias de Figueiró dos Vinhos e Bairradas",
  ],
  'Viana do Alentejo': [
    "Aguiar",
    "Alcáçovas",
    "Viana do Alentejo",
  ],
  'Paredes': [
    "Aguiar de Sousa",
    "Astromil",
    "Baltar",
    "Beire",
    "Cete",
    "Cristelo",
    "Duas Igrejas",
    "Gandra",
    "Lordelo",
    "Louredo",
    "Parada de Todeia",
    "Paredes",
    "Rebordosa",
    "Recarei",
    "Sobreira",
    "Sobrosa",
    "Vandoma",
    "Vilela",
  ],
  'Póvoa de Varzim': [
    "Aguçadoura",
    "Amorim",
    "Argivai",
    "Aver-o-Mar",
    "Balazar",
    "Beiriz",
    "Estela",
    "Laundos",
    "Navais",
    "Póvoa de Varzim",
    "Rates",
    "Terroso",
  ],
  'Guimarães': [
    "Airão (Santa Maria)",
    "Airão São João",
    "Aldão",
    "Azurém",
    "Barco",
    "Brito",
    "Caldelas",
    "Calvos",
    "Candoso (São Martinho)",
    "Conde",
    "Corvite",
    "Costa",
    "Creixomil",
    "Fermentões",
    "Gandarela",
    "Gondar",
    "Gonça",
    "Guardizela",
    "Infantas",
    "Longos",
    "Lordelo",
    "Mesão Frio",
    "Moreira de Cónegos",
    "Nespereira",
    "Pencelo",
    "Pinheiro",
    "Polvoreira",
    "Ponte",
    "Prazins (Santa Eufémia)",
    "Prazins Santo Tirso",
    "Ronfe",
    "Sande (São Clemente)",
    "Sande (São Martinho)",
    "Sande (Vila Nova)",
    "Selho (São Cristóvão)",
    "Selho (São Jorge)",
    "Serzedelo",
    "Serzedo",
    "Silvares",
    "São Faustino",
    "São Torcato",
    "Tabuadelo",
    "União das freguesias de Abação e Gémeos",
    "União das freguesias de Arosa e Castelões",
    "União das freguesias de Atães e Rendufe",
    "União das freguesias de Briteiros Santo Estêvão e Donim",
    "União das freguesias de Briteiros São Salvador e Briteiros Santa Leocádia",
    "União das freguesias de Candoso São Tiago e Mascotelos",
    "União das freguesias de Leitões, Oleiros e Figueiredo",
    "União das freguesias de Oliveira, São Paio e São Sebastião",
    "União das freguesias de Sande São Lourenço e Balazar",
    "União das freguesias de Selho São Lourenço e Gominhães",
    "União das freguesias de Souto Santa Maria, Souto São Salvador e Gondomar",
    "Urgezes",
    "Vermil",
  ],
  'Lisboa': [
    "Ajuda",
    "Alcântara",
    "Alvalade",
    "Areeiro",
    "Arroios",
    "Avenidas Novas",
    "Beato",
    "Belém",
    "Benfica",
    "Campo de Ourique",
    "Campolide",
    "Carnide",
    "Estrela",
    "Lumiar",
    "Marvila",
    "Misericórdia",
    "Olivais",
    "Parque das Nações",
    "Penha de França",
    "Santa Clara",
    "Santa Maria Maior",
    "Santo António",
    "São Domingos de Benfica",
    "São Vicente",
  ],
  'Ponta Delgada': [
    "Ajuda da Bretanha",
    "Arrifes",
    "Candelária",
    "Capelas",
    "Covoada",
    "Fajã de Baixo",
    "Fajã de Cima",
    "Fenais da Luz",
    "Feteiras",
    "Ginetes",
    "Mosteiros",
    "Pilar da Bretanha",
    "Ponta Delgada (São José)",
    "Ponta Delgada (São Pedro)",
    "Ponta Delgada (São Sebastião)",
    "Relva",
    "Remédios",
    "Rosto do Cão (Livramento)",
    "Rosto do Cão (São Roque)",
    "Santa Bárbara",
    "Santa Clara",
    "Santo António",
    "Sete Cidades",
    "São Vicente Ferreira",
  ],
  'Portalegre': [
    "Alagoa",
    "Alegrete",
    "Fortios",
    "União das freguesias da Sé e São Lourenço",
    "União das freguesias de Reguengo e São Julião",
    "União das freguesias de Ribeira de Nisa e Carreiras",
    "Urra",
  ],
  'Albergaria-a-Velha': [
    "Albergaria-a-Velha e Valmaior",
    "Alquerubim",
    "Angeja",
    "Branca",
    "Ribeira de Fráguas",
    "São João de Loure e Frossos",
  ],
  'Albufeira': [
    "Albufeira e Olhos de Água",
    "Ferreiras",
    "Guia",
    "Paderne",
  ],
  'Ourém': [
    "Alburitel",
    "Atouguia",
    "Casal dos Bernardos",
    "Caxarias",
    "Cercal",
    "Espite",
    "Fátima",
    "Gondemaria",
    "Matas",
    "Nossa Senhora da Piedade",
    "Nossa Senhora das Misericórdias",
    "Olival",
    "Rio de Couros",
    "Seiça",
    "União das freguesias de Freixianda, Ribeira do Fárrio e Formigais",
    "Urqueira",
  ],
  'Cascais': [
    "Alcabideche",
    "São Domingos de Rana",
    "União das freguesias de Carcavelos e Parede",
    "União das freguesias de Cascais e Estoril",
  ],
  'Fundão': [
    "Alcaide",
    "Alcaria",
    "Alcongosta",
    "Alpedrinha",
    "Barroca",
    "Bogas de Cima",
    "Capinha",
    "Castelejo",
    "Castelo Novo",
    "Enxames",
    "Fatela",
    "Lavacolhos",
    "Orca",
    "Pêro Viseu",
    "Silvares",
    "Soalheira",
    "Souto da Casa",
    "Telhado",
    "Três Povos",
    "União das freguesias de Fundão, Valverde, Donas, Aldeia de Joanes e Aldeia Nova do Cabo",
    "União das freguesias de Janeiro de Cima e Bogas de Baixo",
    "União das freguesias de Póvoa de Atalaia e Atalaia do Campo",
    "União das freguesias de Vale de Prazeres e Mata da Rainha",
  ],
  'Castelo Branco': [
    "Alcains",
    "Almaceda",
    "Benquerenças",
    "Castelo Branco",
    "Escalos de Baixo",
    "Escalos de Cima",
    "Lardosa",
    "Louriçal do Campo",
    "Lousa",
    "Malpica do Tejo",
    "Mata",
    "Monforte da Beira",
    "Ninho do Açor",
    "Salgueiro do Campo",
    "Santo André das Tojeiras",
    "Sarzedas",
    "Sobral do Campo",
    "São Vicente da Beira",
    "Tinalhas",
    "União das freguesias de Cebolais de Cima e Retaxo",
    "União das freguesias de Freixial e Juncal do Campo",
    "União das freguesias de Póvoa de Rio de Moinhos e Cafede",
  ],
  'Silves': [
    "Alcantarilha",
    "Algoz",
    "Armação de Pêra",
    "Pêra",
    "Silves",
    "São Bartolomeu de Messines",
    "São Marcos da Serra",
    "Tunes",
  ],
  'Sardoal': [
    "Alcaravela",
    "Santiago de Montalegre",
    "Sardoal",
    "Valhascos",
  ],
  'Mértola': [
    "Alcaria Ruiva",
    "Corte do Pinto",
    "Espírito Santo",
    "Mértola",
    "Santana de Cambas",
    "São João dos Caldeireiros",
    "União das freguesias de São Miguel do Pinheiro, São Pedro de Solis e São Sebastião dos Carros",
  ],
  'Rio Maior': [
    "Alcobertas",
    "Arrouquelas",
    "Asseiceira",
    "Fráguas",
    "Rio Maior",
    "São Sebastião",
    "União das freguesias de Azambujeira e Malaqueijo",
    "União das freguesias de Marmeleira e Assentiz",
    "União das freguesias de Outeiro da Cortiçada e Arruda dos Pisões",
    "União das freguesias de São João da Ribeira e Ribeira de São João",
  ],
  'Alcochete': [
    "Alcochete",
    "Samouco",
    "São Francisco",
  ],
  'Azambuja': [
    "Alcoentre",
    "Aveiras de Baixo",
    "Aveiras de Cima",
    "Azambuja",
    "União das freguesias de Manique do Intendente, Vila Nova de São Pedro e Maçussa",
    "Vale do Paraíso",
    "Vila Nova da Rainha",
  ],
  'Vouzela': [
    "Alcofra",
    "Campia",
    "Fornelo do Monte",
    "Queirã",
    "São Miguel do Mato",
    "União das freguesias de Cambra e Carvalhal de Vermilhas",
    "União das freguesias de Fataunços e Figueiredo das Donas",
    "União das freguesias de Vouzela e Paços de Vilharigues",
    "Ventosa",
  ],
  'Alcácer do Sal': [
    "Alcácer do Sal (Santa Maria do Castelo)",
    "Alcácer do Sal (Santiago)",
    "Comporta",
    "Santa Susana",
    "São Martinho",
    "Torrão",
  ],
  'Trancoso': [
    "Aldeia Nova",
    "Castanheira",
    "Cogula",
    "Cótimos",
    "Fiães",
    "Granja",
    "Guilheiro",
    "Moimentinha",
    "Moreira de Rei",
    "Palhais",
    "Póvoa do Concelho",
    "Reboleiro",
    "Rio de Mel",
    "Tamanhos",
    "União das freguesias de Freches e Torres",
    "União das freguesias de Torre do Terrenho, Sebadelhe da Serra e Terrenho",
    "União das freguesias de Trancoso (São Pedro e Santa Maria) e Souto Maior",
    "União das freguesias de Vale do Seixo e Vila Garcia",
    "União das freguesias de Vila Franca das Naves e Feital",
    "União das freguesias de Vilares e Carnicães",
    "Valdujo",
  ],
  'Avis': [
    "Aldeia Velha",
    "Avis",
    "Ervedal",
    "Figueira e Barros",
    "União das freguesias de Alcórrego e Maranhão",
    "União das freguesias de Benavila e Valongo",
  ],
  'Sabugal': [
    "Aldeia Velha",
    "Aldeia da Ponte",
    "Aldeia do Bispo",
    "Alfaiates",
    "Baraçal",
    "Bendada",
    "Bismula",
    "Casteleiro",
    "Cerdeira",
    "Fóios",
    "Malcata",
    "Nave",
    "Quadrazais",
    "Quintas de São Bartolomeu",
    "Rapoula do Côa",
    "Rebolosa",
    "Rendo",
    "Sortelha",
    "Souto",
    "União das freguesias de Aldeia da Ribeira, Vilar Maior e Badamalos",
    "União das freguesias de Lajeosa e Forcalhos",
    "União das freguesias de Pousafoles do Bispo, Pena Lobo e Lomba",
    "União das freguesias de Ruvina, Ruivós e Vale das Éguas",
    "União das freguesias de Santo Estêvão e Moita",
    "União das freguesias de Seixo do Côa e Vale Longo",
    "União das freguesias do Sabugal e Aldeia de Santo António",
    "Vale de Espinho",
    "Vila Boa",
    "Vila do Touro",
    "Águas Belas",
  ],
  'Crato': [
    "Aldeia da Mata",
    "Gáfete",
    "Monte da Pedra",
    "União das freguesias de Crato e Mártires, Flor da Rosa e Vale do Peso",
  ],
  'Oliveira do Hospital': [
    "Aldeia das Dez",
    "Alvoco das Várzeas",
    "Avô",
    "Bobadela",
    "Ervedal",
    "Lagares",
    "Lourosa",
    "Meruge",
    "Nogueira do Cravo",
    "Seixo da Beira",
    "São Gião",
    "Travanca de Lagos",
    "União das freguesias de Lagos da Beira e Lajeosa",
    "União das freguesias de Oliveira do Hospital e São Paio de Gramaços",
    "União das freguesias de Penalva de Alva e São Sebastião da Feira",
    "União das freguesias de Santa Ovaia e Vila Pouca da Beira",
    "Vila Franca da Beira",
  ],
  'Idanha-a-Nova': [
    "Aldeia de Santa Margarida",
    "Ladoeiro",
    "Medelim",
    "Oledo",
    "Penha Garcia",
    "Proença-a-Velha",
    "Rosmaninhal",
    "São Miguel de Acha",
    "Toulões",
    "União das freguesias de Idanha-a-Nova e Alcafozes",
    "União das freguesias de Monfortinho e Salvaterra do Extremo",
    "União das freguesias de Monsanto e Idanha-a-Velha",
    "União das freguesias de Zebreira e Segura",
  ],
  'Covilhã': [
    "Aldeia de São Francisco de Assis",
    "Barco",
    "Boidobra",
    "Cantar-Galo",
    "Casegas",
    "Cortes do Meio",
    "Coutada",
    "Dominguizo",
    "Erada",
    "Ferro",
    "Orjais",
    "Ourondo",
    "Paul",
    "Peraboa",
    "Peso",
    "Sobral de São Miguel",
    "São Jorge da Beira",
    "Tortosendo",
    "Unhais da Serra",
    "União das freguesias de Covilhã e Canhoso",
    "União das freguesias de Teixoso e Sarzedo",
    "União das freguesias de Vale Formoso e Aldeia do Souto",
    "Vales do Rio",
    "Verdelhos",
    "Vila do Carvalho",
  ],
  'Almodôvar': [
    "Aldeia dos Fernandes",
    "Almodôvar",
    "Gomes Aires",
    "Rosário",
    "Santa Clara-a-Nova",
    "Santa Cruz",
    "Senhora da Graça dos Padrões",
    "São Barnabé",
  ],
  'Armamar': [
    "Aldeias",
    "Armamar",
    "Cimbres",
    "Folgosa",
    "Fontelo",
    "Queimada",
    "Queimadela",
    "Santa Cruz",
    "São Cosmado",
    "São Martinho das Chãs",
    "União das freguesias de Aricera e Goujoim",
    "União das freguesias de São Romão e Santiago",
    "União das freguesias de Vila Seca e Santo Adrião",
    "Vacalar",
  ],
  'Bragança': [
    "Alfaião",
    "Babe",
    "Baçal",
    "Carragosa",
    "Castro de Avelãs",
    "Coelhoso",
    "Donai",
    "Espinhosela",
    "França",
    "Gimonde",
    "Gondesende",
    "Gostei",
    "Grijó de Parada",
    "Macedo do Mato",
    "Mós",
    "Nogueira",
    "Outeiro",
    "Parâmio",
    "Pinela",
    "Quintanilha",
    "Quintela de Lampaças",
    "Rabal",
    "Rebordãos",
    "Salsas",
    "Samil",
    "Santa Comba de Rossas",
    "Sendas",
    "Serapicos",
    "Sortes",
    "São Pedro de Sarracenos",
    "União das freguesias de Aveleda e Rio de Onor",
    "União das freguesias de Castrelos e Carrazedo",
    "União das freguesias de Izeda, Calvelhe e Paradinha Nova",
    "União das freguesias de Parada e Faílde",
    "União das freguesias de Rebordainhos e Pombares",
    "União das freguesias de Rio Frio e Milhão",
    "União das freguesias de São Julião de Palácios e Deilão",
    "União das freguesias de Sé, Santa Maria e Meixedo",
    "Zoio",
  ],
  'Vila Pouca de Aguiar': [
    "Alfarela de Jales",
    "Alvão",
    "Bornes de Aguiar",
    "Bragado",
    "Capeludos",
    "Sabroso de Aguiar",
    "Soutelo de Aguiar",
    "Telões",
    "Tresminas",
    "União das freguesias de Pensalvos e Parada de Monteiros",
    "Valoura",
    "Vila Pouca de Aguiar",
    "Vreia de Bornes",
    "Vreia de Jales",
  ],
  'Soure': [
    "Alfarelos",
    "Figueiró do Campo",
    "Granja do Ulmeiro",
    "Samuel",
    "Soure",
    "Tapéus",
    "União das freguesias de Degracias e Pombalinho",
    "União das freguesias de Gesteira e Brunhós",
    "Vila Nova de Anços",
    "Vinha da Rainha",
  ],
  'Alcobaça': [
    "Alfeizerão",
    "Aljubarrota",
    "Benedita",
    "Bárrio",
    "Cela",
    "Maiorga",
    "São Martinho do Porto",
    "Turquel",
    "União das freguesias de Alcobaça e Vestiaria",
    "União das freguesias de Coz, Alpedriz e Montes",
    "União das freguesias de Pataias e Martingança",
    "Vimeiro",
    "Évora de Alcobaça",
  ],
  'Valongo': [
    "Alfena",
    "Campo",
    "Ermesinde",
    "Sobrado",
    "Valongo",
  ],
  'Monchique': [
    "Alferce",
    "Marmelete",
    "Monchique",
  ],
  'Amadora': [
    "Alfragide",
    "Encosta do Sol",
    "Falagueira-Venda Nova",
    "Mina de Água",
    "Venteira",
    "Águas Livres",
  ],
  'Ferreira do Alentejo': [
    "Alfundão",
    "Canhestros",
    "Ferreira do Alentejo",
    "Figueira dos Cavaleiros",
    "Odivelas",
    "Peroguarda",
  ],
  'Alfândega da Fé': [
    "Alfândega da Fé",
    "Cerejais",
    "Sambade",
    "União das freguesias de Agrobom, Saldonha e Vale Pereiro",
    "União das freguesias de Eucisia, Gouveia e Valverde",
    "União das freguesias de Ferradosa e Sendim da Serra",
    "União das freguesias de Gebelim e Soeima",
    "União das freguesias de Parada e Sendim da Ribeira",
    "União das freguesias de Pombal e Vales",
    "Vilar Chão",
    "Vilarelhos",
    "Vilares de Vilariça",
  ],
  'Valpaços': [
    "Algeriz",
    "Bouçoães",
    "Canaveses",
    "Carrazedo de Montenegro e Curros",
    "Ervões",
    "Fornos do Pinhal",
    "Friões",
    "Lebução, Fiães e Nozelos",
    "Padrela e Tazem",
    "Possacos",
    "Rio Torto",
    "Santa Maria de Emeres",
    "Santa Valha",
    "Santiago da Ribeira de Alhariz",
    "Serapicos",
    "Sonim e Barreiros",
    "São João da Corveira",
    "São Pedro de Veiga de Lila",
    "Tinhela e Alvarelhos",
    "Vales",
    "Valpaços e Sanfins",
    "Vassal",
    "Veiga de Lila",
    "Vilarandelo",
    "Água Revés e Crasto",
  ],
  'Fornos de Algodres': [
    "Algodres",
    "Casal Vasco",
    "Figueiró da Granja",
    "Fornos de Algodres",
    "Infias",
    "Maceira",
    "Matança",
    "Muxagata",
    "Queiriz",
    "União das freguesias de Cortiçô e Vila Chã",
    "União das freguesias de Juncais, Vila Ruiva e Vila Soeiro do Chão",
    "União das freguesias de Sobral Pichorro e Fuinhas",
  ],
  'Cadaval': [
    "Alguber",
    "Peral",
    "União das freguesias de Lamas e Cercal",
    "União das freguesias de Painho e Figueiros",
    "União das freguesias do Cadaval e Pêro Moniz",
    "Vermelha",
    "Vilar",
  ],
  'Sintra': [
    "Algueirão-Mem Martins",
    "Almargem do Bispo",
    "Belas",
    "Casal de Cambra",
    "Colares",
    "Montelavar",
    "Pêro Pinheiro",
    "Queluz",
    "Rio de Mouro",
    "São João das Lampas",
    "Terrugem",
    "União das freguesias de Agualva e Mira-Sintra",
    "União das freguesias de Massamá e Monte Abraão",
    "União das freguesias de Sintra (Santa Maria e São Miguel, São Martinho e São Pedro de Penaferrim)",
    "União das freguesias do Cacém e São Marcos",
  ],
  'Figueira da Foz': [
    "Alhadas",
    "Alqueidão",
    "Bom Sucesso",
    "Brenha",
    "Buarcos",
    "Ferreira-a-Nova",
    "Lavos",
    "Maiorca",
    "Marinha das Ondas",
    "Moinhos da Gândara",
    "Paião",
    "Quiaios",
    "Santana",
    "São Julião da Figueira da Foz",
    "São Pedro",
    "Tavarede",
    "Vila Verde",
  ],
  'Moita': [
    "Alhos Vedros",
    "Moita",
    "União das freguesias de Baixa da Banheira e Vale da Amoreira",
    "União das freguesias de Gaio-Rosário e Sarilhos Pequenos",
  ],
  'Alijó': [
    "Alijó",
    "Favaios",
    "Pegarinhos",
    "Pinhão",
    "Sanfins do Douro",
    "Santa Eugénia",
    "São Mamede de Ribatua",
    "União das freguesias de Carlão e Amieiro",
    "União das freguesias de Castedo e Cotas",
    "União das freguesias de Pópulo e Ribalonga",
    "União das freguesias de Vale de Mendiz, Casal de Loivos e Vilarinho de Cotas",
    "Vila Chã",
    "Vila Verde",
    "Vilar de Maçada",
  ],
  'Aljezur': [
    "Aljezur",
    "Bordeira",
    "Odeceixe",
    "Rogil",
  ],
  'Aljustrel': [
    "Aljustrel",
    "Ervidel",
    "Messejana",
    "Rio de Moinhos",
    "São João de Negrilhos",
  ],
  'Vila do Porto': [
    "Almagreira",
    "Santa Bárbara",
    "Santo Espírito",
    "São Pedro",
    "Vila do Porto",
  ],
  'Coimbra': [
    "Almalaguês",
    "Brasfemes",
    "Ceira",
    "Cernache",
    "Santo António dos Olivais",
    "São João do Campo",
    "São Silvestre",
    "Torres do Mondego",
    "União das freguesias de Antuzede e Vil de Matos",
    "União das freguesias de Assafarge e Antanhol",
    "União das freguesias de Coimbra (Sé Nova, Santa Cruz, Almedina e São Bartolomeu)",
    "União das freguesias de Eiras e São Paulo de Frades",
    "União das freguesias de Santa Clara e Castelo Viegas",
    "União das freguesias de Souselas e Botão",
    "União das freguesias de São Martinho de Árvore e Lamarosa",
    "União das freguesias de São Martinho do Bispo e Ribeira de Frades",
    "União das freguesias de Taveiro, Ameal e Arzila",
    "União das freguesias de Trouxemil e Torre de Vilela",
  ],
  'Loulé': [
    "Almancil",
    "Alte",
    "Ameixial",
    "Benafim",
    "Boliqueime",
    "Loulé (São Clemente)",
    "Loulé (São Sebastião)",
    "Quarteira",
    "Querença",
    "Salir",
    "Tôr",
  ],
  'Almeida': [
    "Almeida",
    "Castelo Bom",
    "Freineda",
    "Freixo",
    "Malhada Sorda",
    "Nave de Haver",
    "São Pedro de Rio Seco",
    "União das freguesias de Amoreira, Parada e Cabreira",
    "União das freguesias de Azinhal, Peva e Valverde",
    "União das freguesias de Castelo Mendo, Ade, Monteperobolso e Mesquitela",
    "União das freguesias de Junça e Naves",
    "União das freguesias de Leomil, Mido, Senouras e Aldeia Nova",
    "União das freguesias de Malpartida e Vale de Coelha",
    "União das freguesias de Miuzela e Porto de Ovelha",
    "Vale da Mula",
    "Vilar Formoso",
  ],
  'Almeirim': [
    "Almeirim",
    "Benfica do Ribatejo",
    "Fazendas de Almeirim",
    "Raposa",
  ],
  'Vila Nova de Foz Côa': [
    "Almendra",
    "Castelo Melhor",
    "Cedovim",
    "Chãs",
    "Custóias",
    "Freixo de Numão",
    "Horta",
    "Muxagata",
    "Numão",
    "Santa Comba",
    "Sebadelhe",
    "Seixas",
    "Touça",
    "Vila Nova de Foz Côa",
  ],
  'Castro Daire': [
    "Almofala",
    "Cabril",
    "Castro Daire",
    "Cujó",
    "Gosende",
    "Moledo",
    "Monteiras",
    "Mões",
    "Pepim",
    "Pinheiro",
    "São Joaninho",
    "União das freguesias de Mamouros, Alva e Ribolhos",
    "União das freguesias de Mezio e Moura Morta",
    "União das freguesias de Parada de Ester e Ester",
    "União das freguesias de Picão e Ermida",
    "União das freguesias de Reriz e Gafanhão",
  ],
  'Alvaiázere': [
    "Almoster",
    "Alvaiázere",
    "Maçãs de Dona Maria",
    "Pelmá",
    "Pussos São Pedro",
  ],
  'Nisa': [
    "Alpalhão",
    "Montalvão",
    "Santana",
    "São Matias",
    "Tolosa",
    "União das freguesias de Arez e Amieira do Tejo",
    "União das freguesias de Espírito Santo, Nossa Senhora da Graça e São Simão",
  ],
  'Alpiarça': [
    "Alpiarça",
  ],
  'Porto de Mós': [
    "Alqueidão da Serra",
    "Calvaria de Cima",
    "Juncal",
    "Mira de Aire",
    "Pedreiras",
    "Porto de Mós - São João Baptista e São Pedro",
    "Serro Ventoso",
    "São Bento",
    "União das freguesias de Alvados e Alcaria",
    "União das freguesias de Arrimal e Mendiga",
  ],
  'Portel': [
    "Alqueva",
    "Amieira",
    "Monte do Trigo",
    "Oriola",
    "Portel",
    "Santana",
    "São Bartolomeu do Outeiro",
    "Vera Cruz",
  ],
  'Angra do Heroísmo': [
    "Altares",
    "Angra (Nossa Senhora da Conceição)",
    "Angra (Santa Luzia)",
    "Angra (São Pedro)",
    "Angra (Sé)",
    "Cinco Ribeiras",
    "Doze Ribeiras",
    "Feteira",
    "Porto Judeu",
    "Posto Santo",
    "Raminho",
    "Ribeirinha",
    "Santa Bárbara",
    "Serreta",
    "São Bartolomeu de Regatos",
    "São Bento",
    "São Mateus da Calheta",
    "Terra Chã",
    "Vila de São Sebastião",
  ],
  'Alter do Chão': [
    "Alter do Chão",
    "Chancelaria",
    "Cunheira",
    "Seda",
  ],
  'Castro Marim': [
    "Altura",
    "Azinhal",
    "Castro Marim",
    "Odeleite",
  ],
  'Boticas': [
    "Alturas do Barroso e Cerdedo",
    "Ardãos e Bobadela",
    "Beça",
    "Boticas e Granja",
    "Codessoso, Curros e Fiães do Tâmega",
    "Covas do Barroso",
    "Dornelas",
    "Pinho",
    "Sapiãos",
    "Vilar e Viveiro",
  ],
  'Ribeira de Pena': [
    "Alvadia",
    "Canedo",
    "Santa Marinha",
    "União das freguesias de Cerva e Limões",
    "União das freguesias de Ribeira de Pena (Salvador) e Santo Aleixo de Além-Tâmega",
  ],
  'Melgaço': [
    "Alvaredo",
    "Cousso",
    "Cristoval",
    "Fiães",
    "Gave",
    "Paderne",
    "Penso",
    "São Paio",
    "União das freguesias de Castro Laboreiro e Lamas de Mouro",
    "União das freguesias de Chaviães e Paços",
    "União das freguesias de Parada do Monte e Cubalhão",
    "União das freguesias de Prado e Remoães",
    "União das freguesias de Vila e Roussas",
  ],
  'Trofa': [
    "Alvarelhos",
    "Covelas",
    "Guidões",
    "Muro",
    "União das freguesias de Bougado (São Martinho e Santiago)",
    "União das freguesias de Coronado (São Romão e São Mamede)",
  ],
  'Arouca': [
    "Alvarenga",
    "Chave",
    "Escariz",
    "Fermedo",
    "Mansores",
    "Moldes",
    "Rossas",
    "Santa Eulália",
    "São Miguel do Mato",
    "Tropeço",
    "União das freguesias de Arouca e Burgo",
    "União das freguesias de Cabreiros e Albergaria da Serra",
    "União das freguesias de Canelas e Espiunca",
    "União das freguesias de Covelo de Paivó e Janarde",
    "Urrô",
    "Várzea",
  ],
  'Góis': [
    "Alvares",
    "Góis",
    "União das freguesias de Cadafaz e Colmeal",
    "Vila Nova do Ceira",
  ],
  'Santa Marta de Penaguião': [
    "Alvações do Corgo",
    "Cumieira",
    "Fontes",
    "Lobrigos (São João Baptista)",
    "Lobrigos (São Miguel)",
    "Medrões",
    "Sanhoane",
    "Sever",
    "União das freguesias de Louredo e Fornelos",
  ],
  'Moimenta da Beira': [
    "Alvite",
    "Arcozelos",
    "Baldos",
    "Cabaços",
    "Caria",
    "Castelo",
    "Leomil",
    "Moimenta da Beira",
    "Passô",
    "Sarzedo",
    "Sever",
    "União das freguesias de Paradinha e Nagosa",
    "União das freguesias de Peva e Segões",
    "União das freguesias de Pêra Velha, Aldeia de Nacomba e Ariz",
    "Vila da Rua",
    "Vilar",
  ],
  'Alvito': [
    "Alvito",
    "Vila Nova da Baronia",
  ],
  'Seia': [
    "Alvoco da Serra",
    "Girabolhos",
    "Lapa dos Dinheiros",
    "Loriga",
    "Paranhos",
    "Pinhanços",
    "Sabugueiro",
    "Sandomil",
    "Santa Comba",
    "Santa Marinha",
    "Santiago",
    "Sazes da Beira",
    "Seia",
    "São Martinho",
    "São Romão",
    "Teixeira",
    "Travancinha",
    "União das freguesias de Carragozela e Várzea de Meruge",
    "União das freguesias de Sameice e Santa Eulália",
    "União das freguesias de Torrozelo e Folhadosa",
    "União das freguesias de Tourais e Lajes",
    "União das freguesias de Vide e Cabeça",
    "Valezim",
    "Vila Cova à Coelheira",
  ],
  'Portimão': [
    "Alvor",
    "Mexilhoeira Grande",
    "Portimão",
  ],
  'Ansião': [
    "Alvorge",
    "Ansião",
    "Avelar",
    "Chão de Couce",
    "Pousaflores",
    "Santiago da Guarda",
  ],
  'Moura': [
    "Amareleja",
    "Póvoa de São Miguel",
    "Safara",
    "Santo Aleixo da Restauração",
    "Sobral da Adiça",
    "União das freguesias de Moura (Santo Agostinho e São João Baptista) e Santo Amador",
  ],
  'Macedo de Cavaleiros': [
    "Amendoeira",
    "Arcas",
    "Carrapatas",
    "Chacim",
    "Cortiços",
    "Corujas",
    "Ferreira",
    "Grijó",
    "Lagoa",
    "Lamalonga",
    "Lamas",
    "Lombo",
    "Macedo de Cavaleiros",
    "Morais",
    "Olmos",
    "Peredo",
    "Salselas",
    "Sezulfe",
    "Talhas",
    "União das freguesias de Ala e Vilarinho do Monte",
    "União das freguesias de Bornes e Burga",
    "União das freguesias de Castelãos e Vilar do Monte",
    "União das freguesias de Espadanedo, Edroso, Murçós e Soutelo Mourisco",
    "União das freguesias de Podence e Santa Combinha",
    "União das freguesias de Talhinhas e Bagueixe",
    "Vale Benfeito",
    "Vale da Porca",
    "Vale de Prados",
    "Vilarinho de Agrochão",
    "Vinhas",
  ],
  'Leiria': [
    "Amor",
    "Arrabal",
    "Bajouca",
    "Bidoeira de Cima",
    "Caranguejeira",
    "Carreira",
    "Coimbrão",
    "Maceira",
    "Milagres",
    "Monte Redondo",
    "Ortigosa",
    "Regueira de Pontes",
    "Souto da Carpalhosa",
    "União das freguesias de Colmeias e Memória",
    "União das freguesias de Leiria, Pousos, Barreira e Cortes",
    "União das freguesias de Marrazes e Barosa",
    "União das freguesias de Monte Real e Carvide",
    "União das freguesias de Parceiros e Azoia",
    "União das freguesias de Santa Catarina da Serra e Chainça",
    "União das freguesias de Santa Eufémia e Boa Vista",
  ],
  'Seixal': [
    "Amora",
    "Arrentela",
    "Corroios",
    "Fernão Ferro",
    "Paio Pires",
    "Seixal",
  ],
  'Mação': [
    "Amêndoa",
    "Cardigos",
    "Carvoeiro",
    "Envendos",
    "Ortiga",
    "União das freguesias de Mação, Penhascoso e Aboboreira",
  ],
  'Ponte de Lima': [
    "Anais",
    "Arca e Ponte de Lima",
    "Arcozelo",
    "Ardegão, Freixo e Mato",
    "Beiral do Lima",
    "Bertiandos",
    "Boalhosa",
    "Brandara",
    "Bárrio e Cepões",
    "Cabaços e Fojo Lobal",
    "Cabração e Moreira do Lima",
    "Calheiros",
    "Calvelo",
    "Correlhã",
    "Estorãos",
    "Facha",
    "Feitosa",
    "Fontão",
    "Fornelos e Queijada",
    "Friastelas",
    "Gaifar",
    "Gandra",
    "Gemieira",
    "Gondufe",
    "Labruja",
    "Labrujó, Rendufe e Vilar do Monte",
    "Navió e Vitorino dos Piães",
    "Poiares",
    "Rebordões (Santa Maria)",
    "Rebordões (Souto)",
    "Refóios do Lima",
    "Ribeira",
    "Sandiães",
    "Santa Comba",
    "Santa Cruz do Lima",
    "Seara",
    "Serdedelo",
    "Sá",
    "São Pedro d'Arcos",
    "Vilar das Almas",
    "Vitorino das Donas",
  ],
  'Chaves': [
    "Anelhe",
    "Bustelo",
    "Cimo de Vila da Castanheira",
    "Curalha",
    "Ervededo",
    "Faiões",
    "Lama de Arcos",
    "Mairos",
    "Moreiras",
    "Nogueira da Montanha",
    "Oura",
    "Outeiro Seco",
    "Paradela",
    "Planalto de Monforte (União das freguesias de Oucidres e Bobadela)",
    "Redondelo",
    "Sanfins",
    "Santa Leocádia",
    "Santa Maria Maior",
    "Santo António de Monforte",
    "Santo Estêvão",
    "São Pedro de Agostém",
    "São Vicente",
    "Tronco",
    "União das freguesias da Madalena e Samaiões",
    "União das freguesias das Eiras, São Julião de Montenegro e Cela",
    "União das freguesias de Calvão e Soutelinho da Raia",
    "União das freguesias de Loivos e Póvoa de Agrações",
    "União das freguesias de Santa Cruz/Trindade e Sanjurge",
    "União das freguesias de Soutelo e Seara Velha",
    "União das freguesias de Travancas e Roriz",
    "Vale de Anta",
    "Vidago (União das freguesias de Vidago, Arcossó, Selhariz e Vilarinho das Paranheiras)",
    "Vila Verde da Raia",
    "Vilar de Nantes",
    "Vilarelho da Raia",
    "Vilas Boas",
    "Vilela Seca",
    "Vilela do Tâmega",
    "Águas Frias",
  ],
  'Condeixa-a-Nova': [
    "Anobra",
    "Ega",
    "Furadouro",
    "União das freguesias de Condeixa-a-Velha e Condeixa-a-Nova",
    "União das freguesias de Sebal e Belide",
    "União das freguesias de Vila Seca e Bem da Fé",
    "Zambujal",
  ],
  'Espinho': [
    "Anta",
    "Espinho",
    "Guetim",
    "Paramos",
    "Silvalde",
  ],
  'Esposende': [
    "Antas",
    "Apúlia",
    "Belinho",
    "Curvos",
    "Esposende",
    "Forjães",
    "Fão",
    "Gandra",
    "Gemeses",
    "Mar",
    "Marinhas",
    "Palmeira de Faro",
    "União das freguesias de Fonte Boa e Rio Tinto",
    "Vila Chã",
  ],
  'Mealhada': [
    "Antes",
    "Barcouço",
    "Casal Comba",
    "Luso",
    "Mealhada",
    "Pampilhosa",
    "Vacariça",
    "Ventosa do Bairro",
  ],
  'Cantanhede': [
    "Ançã",
    "Cadima",
    "Cantanhede",
    "Cordinhã",
    "Febres",
    "Murtede",
    "Ourentã",
    "Pocariça",
    "Sanguinheira",
    "São Caetano",
    "Tocha",
    "União das freguesias de Covões e Camarneira",
    "União das freguesias de Portunhos e Outil",
    "União das freguesias de Sepins e Bolho",
    "União das freguesias de Vilamar e Corticeiro de Cima",
  ],
  'Ovar': [
    "Arada",
    "Cortegaça",
    "Esmoriz",
    "Maceda",
    "Ovar",
    "São João",
    "São Vicente de Pereira Jusã",
    "Válega",
  ],
  'Aveiro': [
    "Aradas",
    "Cacia",
    "Eixo e Eirol",
    "Esgueira",
    "Oliveirinha",
    "Requeixo, Nossa Senhora de Fátima e Nariz",
    "Santa Joana",
    "São Bernardo",
    "São Jacinto",
    "União das freguesias de Glória e Vera Cruz",
  ],
  'Penamacor': [
    "Aranhas",
    "Benquerença",
    "Meimoa",
    "Meimão",
    "Penamacor",
    "Salvador",
    "União das freguesias de Aldeia do Bispo, Águas e Aldeia de João Pires",
    "União das freguesias de Pedrógão de São Pedro e Bemposta",
    "Vale da Senhora da Póvoa",
  ],
  'Montemor-o-Velho': [
    "Arazede",
    "Carapinheira",
    "Ereira",
    "Liceia",
    "Meãs do Campo",
    "Pereira",
    "Santo Varão",
    "Seixo de Gatões",
    "Tentúgal",
    "União das freguesias de Abrunheira, Verride e Vila Nova da Barca",
    "União das freguesias de Montemor-o-Velho e Gatões",
  ],
  'Calheta': [
    "Arco da Calheta",
    "Calheta",
    "Estreito da Calheta",
    "Fajã da Ovelha",
    "Jardim do Mar",
    "Paul do Mar",
    "Ponta do Pargo",
    "Prazeres",
  ],
  'Santana': [
    "Arco de São Jorge",
    "Faial",
    "Ilha",
    "Santana",
    "São Jorge",
    "São Roque do Faial",
  ],
  'Estremoz': [
    "Arcos",
    "Glória",
    "São Domingos de Ana Loura",
    "União das freguesias de Estremoz (Santa Maria e Santo André)",
    "União das freguesias de São Bento do Cortiço e Santo Estêvão",
    "União das freguesias de São Lourenço de Mamporcão e São Bento de Ana Loura",
    "União das freguesias do Ameixial (Santa Vitória e São Bento)",
    "Veiros",
    "Évora Monte (Santa Maria)",
  ],
  'Vila do Conde': [
    "Arcos",
    "Aveleda",
    "Azurara",
    "Canidelo",
    "Fajozes",
    "Fornelo",
    "Gião",
    "Guilhabreu",
    "Junqueira",
    "Labruge",
    "Macieira da Maia",
    "Malta",
    "Mindelo",
    "Modivas",
    "Retorta",
    "Rio Mau",
    "Tougues",
    "União das freguesias de Bagunte, Ferreiró, Outeiro Maior e Parada",
    "União das freguesias de Touguinha e Touguinhó",
    "União das freguesias de Vilar e Mosteiró",
    "Vairão",
    "Vila Chã",
    "Vila do Conde",
    "Vilar de Pinheiro",
    "Árvore",
  ],
  'Gouveia': [
    "Arcozelo",
    "Cativelos",
    "Folgosinho",
    "Gouveia",
    "Nespereira",
    "Paços da Serra",
    "Ribamondego",
    "São Paio",
    "União das freguesias de Aldeias e Mangualde da Serra",
    "União das freguesias de Figueiró da Serra e Freixo da Serra",
    "União das freguesias de Melo e Nabais",
    "União das freguesias de Moimenta da Serra e Vinhó",
    "União das freguesias de Rio Torto e Lagarinhos",
    "Vila Cortês da Serra",
    "Vila Franca da Serra",
    "Vila Nova de Tazem",
  ],
  'Vila Nova de Gaia': [
    "Arcozelo",
    "Avintes",
    "Canelas",
    "Canidelo",
    "Crestuma",
    "Grijó",
    "Gulpilhares",
    "Lever",
    "Madalena",
    "Mafamude",
    "Olival",
    "Oliveira do Douro",
    "Pedroso",
    "Perosinho",
    "Sandim",
    "Santa Marinha",
    "Seixezelo",
    "Sermonde",
    "Serzedo",
    "São Félix da Marinha",
    "São Pedro da Afurada",
    "Valadares",
    "Vilar de Andorinho",
    "Vilar do Paraíso",
  ],
  'Oliveira de Frades': [
    "Arcozelo das Maias",
    "Pinheiro",
    "Ribeiradio",
    "São João da Serra",
    "São Vicente de Lafões",
    "União das freguesias de Arca e Varzielas",
    "União das freguesias de Destriz e Reigoso",
    "União das freguesias de Oliveira de Frades, Souto de Lafões e Sejães",
  ],
  'Arganil': [
    "Arganil",
    "Benfeita",
    "Celavisa",
    "Folques",
    "Piódão",
    "Pomares",
    "Pombeiro da Beira",
    "Sarzedo",
    "Secarias",
    "São Martinho da Cortiça",
    "União das freguesias de Cepos e Teixeira",
    "União das freguesias de Cerdeira e Moura da Serra",
    "União das freguesias de Côja e Barril de Alva",
    "União das freguesias de Vila Cova de Alva e Anseriz",
  ],
  'Caminha': [
    "Argela",
    "Dem",
    "Lanhelas",
    "Riba de Âncora",
    "Seixas",
    "União das freguesias de Arga (Baixo, Cima e São João)",
    "União das freguesias de Caminha (Matriz) e Vilarelho",
    "União das freguesias de Gondar e Orbacém",
    "União das freguesias de Moledo e Cristelo",
    "União das freguesias de Venade e Azevedo",
    "Vila Praia de Âncora",
    "Vilar de Mouros",
    "Vile",
    "Âncora",
  ],
  'Santa Maria da Feira': [
    "Argoncilhe",
    "Arrifana",
    "Caldas de São Jorge",
    "Canedo",
    "Escapães",
    "Fiães",
    "Fornos",
    "Gião",
    "Guisande",
    "Lobão",
    "Louredo",
    "Lourosa",
    "Milheirós de Poiares",
    "Mosteirô",
    "Mozelos",
    "Nogueira da Regedoura",
    "Paços de Brandão",
    "Pigeiros",
    "Rio Meão",
    "Romariz",
    "Sanguedo",
    "Santa Maria de Lamas",
    "São João de Ver",
    "São Miguel de Souto",
    "São Paio de Oleiros",
    "União das freguesias de Santa Maria da Feira, Travanca, Sanfins e Espargo",
    "Vale",
    "Vila Maior",
  ],
  'Vimioso': [
    "Argozelo",
    "Carção",
    "Matela",
    "Pinelo",
    "Santulhão",
    "União das freguesias de Algoso, Campo de Víboras e Uva",
    "União das freguesias de Caçarelhos e Angueira",
    "União das freguesias de Vale de Frades e Avelanoso",
    "Vilar Seco",
    "Vimioso",
  ],
  'Fafe': [
    "Armil",
    "Arões (Santa Cristina)",
    "Arões (São Romão)",
    "Estorãos",
    "Fafe",
    "Fornelos",
    "Golães",
    "Medelo",
    "Paços",
    "Quinchães",
    "Regadas",
    "Revelhe",
    "Ribeiros",
    "Silvares (São Martinho)",
    "São Gens",
    "Travassós",
    "União de freguesias de Aboim, Felgueiras, Gontim e Pedraído",
    "União de freguesias de Agrela e Serafão",
    "União de freguesias de Antime e Silvares (São Clemente)",
    "União de freguesias de Ardegão, Arnozela e Seidões",
    "União de freguesias de Cepães e Fareja",
    "União de freguesias de Freitas e Vila Cova",
    "União de freguesias de Monte e Queimadela",
    "União de freguesias de Moreira do Rei e Várzea Cova",
    "Vinhós",
  ],
  'Sernancelhe': [
    "Arnas",
    "Carregal",
    "Chosendo",
    "Cunha",
    "Faia",
    "Granjal",
    "Lamosa",
    "Quintela",
    "União das freguesias de Ferreirim e Macieira",
    "União das freguesias de Fonte Arcada e Escurquela",
    "União das freguesias de Penso e Freixinho",
    "União das freguesias de Sernancelhe e Sarzeda",
    "Vila da Ponte",
  ],
  'Arraiolos': [
    "Arraiolos",
    "Gafanhoeira (São Pedro)",
    "Igrejinha",
    "Sabugueiro",
    "União das freguesias de São Gregório e Santa Justa",
    "Vimieiro",
  ],
  'Arruda dos Vinhos': [
    "Arranhó",
    "Arruda dos Vinhos",
    "Cardosas",
    "S. Tiago dos Velhos",
  ],
  'Vila Nova de Poiares': [
    "Arrifana",
    "Lavegadas",
    "Poiares (Santo André)",
    "São Miguel de Poiares",
  ],
  'Vale de Cambra': [
    "Arões",
    "Cepelos",
    "Junqueira",
    "Macieira de Cambra",
    "Roge",
    "São Pedro de Castelões",
    "União das freguesias de Vila Chã, Codal e Vila Cova de Perrinho",
  ],
  'Tomar': [
    "Asseiceira",
    "Carregueiros",
    "Junceira",
    "Olalhas",
    "Paialvo",
    "Sabacheira",
    "Serra",
    "São Pedro de Tomar",
    "União das freguesias de Além da Ribeira e Pedreira",
    "União das freguesias de Casais e Alviobeira",
    "União das freguesias de Madalena e Beselga",
    "União das freguesias de Tomar (São João Baptista) e Santa Maria dos Olivais",
  ],
  'Torres Novas': [
    "Assentiz",
    "Chancelaria",
    "Meia Via",
    "Pedrógão",
    "Riachos",
    "União das freguesias de Brogueira, Parceiros de Igreja e Alcorochel",
    "União das freguesias de Olaia e Paço",
    "União das freguesias de Torres Novas (Santa Maria, Salvador e Santiago)",
    "União das freguesias de Torres Novas (São Pedro), Lapas e Ribeira Branca",
    "Zibreira",
  ],
  'Monforte': [
    "Assumar",
    "Monforte",
    "Santo Aleixo",
    "Vaiamonte",
  ],
  'Arronches': [
    "Assunção",
    "Esperança",
    "Mosteiros",
  ],
  'Elvas': [
    "Assunção, Ajuda, Salvador e Santo Ildefonso",
    "Caia, São Pedro e Alcáçova",
    "Santa Eulália",
    "São Brás e São Lourenço",
    "São Vicente e Ventosa",
    "Terrugem",
    "União das freguesias de Barbacena e Vila Fernando",
    "Vila Boim",
  ],
  'Lourinhã': [
    "Atalaia",
    "Lourinhã",
    "Moita dos Ferreiros",
    "Reguengo Grande",
    "Ribamar",
    "Santa Bárbara",
    "União das freguesias de Miragaia e Marteleira",
    "União das freguesias de São Bartolomeu dos Galegos e Moledo",
    "Vimeiro",
  ],
  'Vila Nova da Barquinha': [
    "Atalaia",
    "Praia do Ribatejo",
    "Tancos",
    "Vila Nova da Barquinha",
  ],
  'Mondim de Basto': [
    "Atei",
    "Bilhó",
    "São Cristóvão de Mondim de Basto",
    "União das freguesias de Campanhó e Paradança",
    "União das freguesias de Ermelo e Pardelhas",
    "Vilar de Ferreiros",
  ],
  'Peniche': [
    "Atouguia da Baleia",
    "Ferrel",
    "Peniche",
    "Serra d'El-Rei",
  ],
  'Estarreja': [
    "Avanca",
    "Beduído",
    "Pardilhó",
    "Salreu",
    "União das freguesias de Canelas e Fermelã",
    "Veiros",
  ],
  'Sátão': [
    "Avelal",
    "Ferreira de Aves",
    "Mioma",
    "Rio de Moinhos",
    "Silvã de Cima",
    "Sátão",
    "São Miguel de Vila Boa",
    "União das freguesias de Romãs, Decermilo e Vila Longa",
    "União das freguesias de Águas Boas e Forles",
  ],
  'Mêda': [
    "Aveloso",
    "Barreira",
    "Coriscada",
    "Longroiva",
    "Marialva",
    "Mêda, Outeiro de Gatos e Fonte Longa",
    "Poço do Canto",
    "Prova e Casteição",
    "Rabaçal",
    "Ranhados",
    "União das freguesias de Vale Flor, Carvalhal e Pai Penela",
  ],
  'Anadia': [
    "Avelãs de Caminho",
    "Avelãs de Cima",
    "Moita",
    "Sangalhos",
    "São Lourenço do Bairro",
    "União das freguesias de Amoreira da Gândara, Paredes do Bairro e Ancas",
    "União das freguesias de Arcos e Mogofores",
    "União das freguesias de Tamengos, Aguim e Óis do Bairro",
    "Vila Nova de Monsarros",
    "Vilarinho do Bairro",
  ],
  'Vila Nova de Famalicão': [
    "Avidos",
    "Bairro",
    "Brufe",
    "Cabeçudos",
    "Castelões",
    "Cavalões",
    "Cruz",
    "Delães",
    "Esmeriz",
    "Fradelos",
    "Gavião",
    "Gondifelos",
    "Joane",
    "Lagoa",
    "Landim",
    "Louro",
    "Lousado",
    "Mogege",
    "Nine",
    "Novais",
    "Oliveira (Santa Maria)",
    "Oliveira (São Mateus)",
    "Outiz",
    "Pedome",
    "Pousada de Saramagos",
    "Requião",
    "Riba de Ave",
    "Ribeirão",
    "Ruivães",
    "União das freguesias de Antas e Abade de Vermoim",
    "União das freguesias de Arnoso (Santa Maria e Santa Eulália) e Sezures",
    "União das freguesias de Carreira e Bente",
    "União das freguesias de Lemenhe, Mouquim e Jesufrei",
    "União das freguesias de Seide",
    "União das freguesias de Vale (São Cosme), Telhado e Portela",
    "União das freguesias de Vila Nova de Famalicão e Calendário",
    "Vale (São Martinho)",
    "Vermoim",
    "Vilarinho das Cambas",
  ],
  'Lamego': [
    "Avões",
    "Britiande",
    "Cambres",
    "Ferreirim",
    "Ferreiros de Avões",
    "Figueira",
    "Lalim",
    "Lamego (Almacave e Sé)",
    "Lazarim",
    "Penajóia",
    "Penude",
    "Samodães",
    "Sande",
    "União das freguesias de Bigorne, Magueija e Pretarouca",
    "União das freguesias de Cepões, Meijinhos e Melcões",
    "União das freguesias de Parada do Bispo e Valdigem",
    "Vila Nova de Souto d'El-Rei",
    "Várzea de Abrunhais",
  ],
  'Ponte da Barca': [
    "Azias",
    "Boivães",
    "Bravães",
    "Britelo",
    "Cuide de Vila Verde",
    "Lavradas",
    "Lindoso",
    "Nogueira",
    "Oleiros",
    "Sampriz",
    "União das freguesias de Crasto, Ruivos e Grovelas",
    "União das freguesias de Entre Ambos-os-Rios, Ermida e Germil",
    "União das freguesias de Ponte da Barca, Vila Nova de Muía e Paço Vedro de Magalhães",
    "União das freguesias de Touvedo (São Lourenço e Salvador)",
    "União das freguesias de Vila Chã (São João Baptista e Santiago)",
    "Vade (São Pedro)",
    "Vade (São Tomé)",
  ],
  'Golegã': [
    "Azinhaga",
    "Golegã",
    "Pombalinho",
  ],
  'Grândola': [
    "Azinheira dos Barros e São Mamede do Sádão",
    "Carvalhal",
    "Melides",
    "União das freguesias de Grândola e Santa Margarida da Serra",
  ],
  'Mogadouro': [
    "Azinhoso",
    "Bemposta",
    "Brunhoso",
    "Bruçó",
    "Castelo Branco",
    "Castro Vicente",
    "Meirinhos",
    "Paradela",
    "Penas Roias",
    "Peredo da Bemposta",
    "Saldanha",
    "São Martinho do Peso",
    "Travanca",
    "Tó",
    "União das freguesias de Brunhozinho, Castanheira e Sanhoane",
    "União das freguesias de Mogadouro, Valverde, Vale de Porco e Vilar de Rei",
    "União das freguesias de Remondes e Soutelo",
    "União das freguesias de Vilarinho dos Galegos e Ventozelo",
    "Urrós",
    "Vale da Madre",
    "Vila de Ala",
  ],
  'Torre de Moncorvo': [
    "Açoreira",
    "Cabeça Boa",
    "Carviçais",
    "Castedo",
    "Horta da Vilariça",
    "Larinho",
    "Lousa",
    "Mós",
    "Torre de Moncorvo",
    "União das freguesias de Adeganha e Cardanha",
    "União das freguesias de Felgar e Souto da Velha",
    "União das freguesias de Felgueiras e Maçores",
    "União das freguesias de Urros e Peredo dos Castelhanos",
  ],
  'Gondomar': [
    "Baguim do Monte (Rio Tinto)",
    "Lomba",
    "Rio Tinto",
    "União das freguesias de Foz do Sousa e Covelo",
    "União das freguesias de Fânzeres e São Pedro da Cova",
    "União das freguesias de Gondomar (São Cosme), Valbom e Jovim",
    "União das freguesias de Melres e Medas",
  ],
  'Terras de Bouro': [
    "Balança",
    "Campo do Gerês",
    "Carvalheira",
    "Covide",
    "Gondoriz",
    "Moimenta",
    "Ribeira",
    "Rio Caldo",
    "Souto",
    "União das freguesias de Chamoim e Vilar",
    "União das freguesias de Chorense e Monte",
    "União das freguesias de Cibões e Brufe",
    "Valdosende",
    "Vilar da Veiga",
  ],
  'Beja': [
    "Baleizão",
    "Beringel",
    "Cabeça Gorda",
    "Nossa Senhora das Neves",
    "Santa Clara de Louredo",
    "São Matias",
    "União das freguesias de Albernoa e Trindade",
    "União das freguesias de Beja (Salvador e Santa Maria da Feira)",
    "União das freguesias de Beja (Santiago Maior e São João Baptista)",
    "União das freguesias de Salvada e Quintos",
    "União das freguesias de Santa Vitória e Mombeja",
    "União das freguesias de Trigaches e São Brissos",
  ],
  'Madalena': [
    "Bandeiras",
    "Candelária",
    "Criação Velha",
    "Madalena",
    "São Caetano",
    "São Mateus",
  ],
  'Celorico da Beira': [
    "Baraçal",
    "Carrapichana",
    "Casas do Soeiro",
    "Forno Telheiro",
    "Lajeosa do Mondego",
    "Linhares",
    "Maçal do Chão",
    "Mesquitela",
    "Minhocal",
    "Prados",
    "Ratoeira",
    "União das freguesias de Açores e Velosa",
    "União das freguesias de Celorico (São Pedro e Santa Maria) e Vila Boa do Mondego",
    "União das freguesias de Cortiçô da Serra, Vide entre Vinhas e Salgueirais",
    "União das freguesias de Rapa e Cadafaz",
    "Vale de Azares",
  ],
  'Oeiras': [
    "Barcarena",
    "Porto Salvo",
    "União das freguesias de Algés, Linda-a-Velha e Cruz Quebrada-Dafundo",
    "União das freguesias de Carnaxide e Queijas",
    "União das freguesias de Oeiras e São Julião da Barra, Paço de Arcos e Caxias",
  ],
  'Mesão Frio': [
    "Barqueiros",
    "Cidadelhe",
    "Mesão Frio (Santo André)",
    "Oliveira",
    "Vila Marim",
  ],
  'Barrancos': [
    "Barrancos",
  ],
  'Tondela': [
    "Barreiro de Besteiros",
    "Campo de Besteiros",
    "Canas de Santa Maria",
    "Castelões",
    "Dardavaz",
    "Ferreirós do Dão",
    "Guardão",
    "Lajeosa do Dão",
    "Lobão da Beira",
    "Molelos",
    "Mosteiro de Fráguas",
    "Parada de Gonta",
    "Sabugosa",
    "Santiago de Besteiros",
    "São Miguel do Outeiro",
    "Tonda",
    "Tourigo",
    "União das freguesias de Caparrosa e Silvares",
    "União das freguesias de Mouraz e Vila Nova da Rainha",
    "União das freguesias de São João do Monte e Mosteirinho",
    "União das freguesias de Tondela e Nandufe",
    "Vilar de Besteiros",
  ],
  'Amares': [
    "Barreiros",
    "Bico",
    "Bouro (Santa Maria)",
    "Bouro (Santa Marta)",
    "Caires",
    "Carrazedo",
    "Dornelas",
    "Fiscal",
    "Goães",
    "Lago",
    "Rendufe",
    "União das freguesias de Amares e Figueiredo",
    "União das freguesias de Caldelas, Sequeiros e Paranhos",
    "União das freguesias de Ferreiros, Prozelo e Besteiros",
    "União das freguesias de Torre e Portela",
    "União das freguesias de Vilela, Seramil e Paredes Secas",
  ],
  'Benavente': [
    "Barrosa",
    "Benavente",
    "Samora Correia",
    "Santo Estêvão",
  ],
  'Lagos': [
    "Barão de São João",
    "Bensafrim",
    "Luz",
    "Odiáxere",
    "São Gonçalo de Lagos",
  ],
  'Vila do Bispo': [
    "Barão de São Miguel",
    "Budens",
    "Sagres",
    "Vila do Bispo e Raposeira",
  ],
  'Batalha': [
    "Batalha",
    "Golpilheira",
    "Reguengo do Fetal",
    "São Mamede",
  ],
  'Ferreira do Zêzere': [
    "Beco",
    "Chãos",
    "Ferreira do Zêzere",
    "Igreja Nova do Sobral",
    "Nossa Senhora do Pranto",
    "União das freguesias de Areias e Pias",
    "Águas Belas",
  ],
  'Carregal do Sal': [
    "Beijós",
    "Cabanas de Viriato",
    "Carregal do Sal",
    "Oliveira do Conde",
    "Parada",
  ],
  'Marvão': [
    "Beirã",
    "Santa Maria de Marvão",
    "Santo António das Areias",
    "São Salvador da Aramenha",
  ],
  'Belmonte': [
    "Belmonte",
    "Caria",
    "Colmeal da Torre",
    "Inguias",
    "Maçainhas",
  ],
  'Gavião': [
    "Belver",
    "Comenda",
    "Margem",
    "União das freguesias de Gavião e Atalaia",
  ],
  'Abrantes': [
    "Bemposta",
    "Carvalhal",
    "Fontes",
    "Martinchel",
    "Mouriscas",
    "Pego",
    "Rio de Moinhos",
    "Tramagal",
    "União das freguesias de Abrantes (São Vicente e São João) e Alferrarede",
    "União das freguesias de Aldeia do Mato e Souto",
    "União das freguesias de Alvega e Concavada",
    "União das freguesias de São Facundo e Vale das Mós",
    "União das freguesias de São Miguel do Rio Torto e Rossio ao Sul do Tejo",
  ],
  'Vila Viçosa': [
    "Bencatel",
    "Ciladas",
    "Nossa Senhora da Conceição e São Bartolomeu",
    "Pardais",
  ],
  'Vila Flor': [
    "Benlhevai",
    "Freixiel",
    "Roios",
    "Sampaio",
    "Samões",
    "Santa Comba de Vilariça",
    "Seixo de Manhoses",
    "Trindade",
    "União das freguesias de Assares e Lodões",
    "União das freguesias de Candoso e Carvalho de Egas",
    "União das freguesias de Valtorno e Mourão",
    "União das freguesias de Vila Flor e Nabo",
    "União das freguesias de Vilas Boas e Vilarinho das Azenhas",
    "Vale Frechoso",
  ],
  'Penedono': [
    "Beselga",
    "Castainço",
    "Penela da Beira",
    "Póvoa de Penela",
    "Souto",
    "União das freguesias de Antas e Ourozinho",
    "União das freguesias de Penedono e Granja",
  ],
  'Odemira': [
    "Bicos",
    "Boavista dos Pinheiros",
    "Colos",
    "Longueira/Almograve",
    "Luzianes-Gare",
    "Relíquias",
    "Sabóia",
    "Santa Clara-a-Velha",
    "São Luís",
    "São Martinho das Amoreiras",
    "São Salvador e Santa Maria",
    "São Teotónio",
    "Vale de Santiago",
    "Vila Nova de Milfontes",
  ],
  'Coruche': [
    "Biscainho",
    "Branca",
    "Coruche",
    "Couço",
    "Erra",
    "Fajarda",
    "Santana do Mato",
    "São José da Lamarosa",
  ],
  'São Vicente': [
    "Boa Ventura",
    "Ponta Delgada",
    "São Vicente",
  ],
  'Valença': [
    "Boivão",
    "Cerdal",
    "Fontoura",
    "Friestas",
    "Ganfei",
    "São Pedro da Torre",
    "União das freguesias de Gandra e Taião",
    "União das freguesias de Gondomil e Sanfins",
    "União das freguesias de São Julião e Silva",
    "União das freguesias de Valença, Cristelo Covo e Arão",
    "Verdoejo",
  ],
  'Porto': [
    "Bonfim",
    "Campanhã",
    "Paranhos",
    "Ramalde",
    "União das freguesias de Aldoar, Foz do Douro e Nevogilde",
    "União das freguesias de Cedofeita, Santo Ildefonso, Sé, Miragaia, São Nicolau e Vitória",
    "União das freguesias de Lordelo do Ouro e Massarelos",
  ],
  'Borba': [
    "Borba (Matriz)",
    "Borba (São Bartolomeu)",
    "Orada",
    "Rio de Moinhos",
  ],
  'São Pedro do Sul': [
    "Bordonhos",
    "Figueiredo de Alva",
    "Manhouce",
    "Pindelo dos Milagres",
    "Pinho",
    "Serrazes",
    "Sul",
    "São Félix",
    "União das freguesias de Carvalhais e Candal",
    "União das freguesias de Santa Cruz da Trapa e São Cristóvão de Lafões",
    "União das freguesias de São Martinho das Moitas e Covas do Rio",
    "União das freguesias de São Pedro do Sul, Várzea e Baiões",
    "Valadares",
    "Vila Maior",
  ],
  'Serpa': [
    "Brinches",
    "Pias",
    "União das freguesias de Serpa (Salvador e Santa Maria)",
    "Vale de Vargo",
    "Vila Nova de São Bento",
    "Vila Verde de Ficalho",
  ],
  'Mora': [
    "Brotas",
    "Cabeção",
    "Mora",
    "Pavia",
  ],
  'Loures': [
    "Bucelas",
    "Fanhões",
    "Loures",
    "Lousa",
    "União das freguesias de Camarate, Unhos e Apelação",
    "União das freguesias de Moscavide e Portela",
    "União das freguesias de Sacavém e Prior Velho",
    "União das freguesias de Santa Iria de Azoia, São João da Talha e Bobadela",
    "União das freguesias de Santo Antão e São Julião do Tojal",
    "União das freguesias de Santo António dos Cavaleiros e Frielas",
  ],
  'Alcanena': [
    "Bugalhos",
    "Minde",
    "Moitas Venda",
    "Monsanto",
    "Serra de Santo António",
    "União das freguesias de Alcanena e Vila Moreira",
    "União das freguesias de Malhou, Louriceira e Espinheiro",
  ],
  'Murtosa': [
    "Bunheiro",
    "Monte",
    "Murtosa",
    "Torreira",
  ],
  'Tavira': [
    "Cabanas de Tavira",
    "Cachopo",
    "Conceição",
    "Luz de Tavira",
    "Santa Catarina da Fonte do Bispo",
    "Santa Luzia",
    "Santo Estêvão",
    "União das freguesias de Tavira (Santa Maria e Santiago)",
  ],
  'Fronteira': [
    "Cabeço de Vide",
    "Fronteira",
    "São Saturnino",
  ],
  'Sertã': [
    "Cabeçudo",
    "Carvalhal",
    "Castelo",
    "Pedrógão Pequeno",
    "Sertã",
    "Troviscal",
    "União das freguesias de Cernache do Bonjardim, Nesperal e Palhais",
    "União das freguesias de Cumeada e Marmeleiro",
    "União das freguesias de Ermida e Figueiredo",
    "Várzea dos Cavaleiros",
  ],
  'Lagoa (Açores)': [
    "Cabouco",
    "Lagoa (Nossa Senhora do Rosário)",
    "Lagoa (Santa Cruz)",
    "Ribeira Chã",
    "Água de Pau",
  ],
  'Montemor-o-Novo': [
    "Cabrela",
    "Ciborro",
    "Cortiçadas de Lavre",
    "Foros de Vale de Figueira",
    "Lavre",
    "Nossa Senhora da Vila",
    "Nossa Senhora do Bispo",
    "Santiago do Escoural",
    "Silveiras",
    "São Cristóvão",
  ],
  'Montalegre': [
    "Cabril",
    "Cervos",
    "Chã",
    "Covelo do Gerês",
    "Ferral",
    "Gralhas",
    "Morgade",
    "Negrões",
    "Outeiro",
    "Pitões das Junias",
    "Reigoso",
    "Salto",
    "Santo André",
    "Sarraquinhos",
    "Solveira",
    "Tourém",
    "União das freguesias de Cambeses do Rio, Donões e Mourilhe",
    "União das freguesias de Meixedo e Padornelos",
    "União das freguesias de Montalegre e Padroso",
    "União das freguesias de Paradela, Contim e Fiães",
    "União das freguesias de Sezelhe e Covelães",
    "União das freguesias de Venda Nova e Pondras",
    "União das freguesias de Viade de Baixo e Fervidelas",
    "União das freguesias de Vilar de Perdizes e Meixide",
    "Vila da Ponte",
  ],
  'Pampilhosa da Serra': [
    "Cabril",
    "Dornelas do Zêzere",
    "Fajão-Vidual",
    "Janeiro de Baixo",
    "Pampilhosa da Serra",
    "Pessegueiro",
    "Portela do Fojo-Machio",
    "Unhais-o-Velho",
  ],
  'Calheta de São Jorge': [
    "Calheta",
    "Norte Pequeno",
    "Ribeira Seca",
    "Santo Antão",
    "Topo (Nossa Senhora do Rosário)",
  ],
  'Lajes do Pico': [
    "Calheta de Nesquim",
    "Lajes do Pico",
    "Piedade",
    "Ribeiras",
    "Ribeirinha",
    "São João",
  ],
  'Ribeira Grande': [
    "Calhetas",
    "Fenais da Ajuda",
    "Lomba da Maia",
    "Lomba de São Pedro",
    "Maia",
    "Pico da Pedra",
    "Porto Formoso",
    "Rabo de Peixe",
    "Ribeira Grande (Conceição)",
    "Ribeira Grande (Matriz)",
    "Ribeira Seca",
    "Ribeirinha",
    "Santa Bárbara",
    "São Brás",
  ],
  'Vagos': [
    "Calvão",
    "Covão do Lobo",
    "Fonte de Angeão",
    "Gafanha da Boa Hora",
    "Ouca",
    "Ponte de Vagos",
    "Santa Catarina",
    "Santo André de Vagos",
    "Santo António",
    "Sosa",
    "Vagos",
  ],
  'Santa Cruz': [
    "Camacha",
    "Caniço",
    "Gaula",
    "Santa Cruz",
    "Santo António da Serra",
  ],
  'Oleiros': [
    "Cambas",
    "Estreito-Vilar Barroco",
    "Isna",
    "Madeirã",
    "Mosteiro",
    "Oleiros-Amieira",
    "Orvalho",
    "Sarnadas de São Simão",
    "Sobral",
    "Álvaro",
  ],
  'Ribeira Brava': [
    "Campanário",
    "Ribeira Brava",
    "Serra de Água",
    "Tabua",
  ],
  'Nelas': [
    "Canas de Senhorim",
    "Lapa do Lobo",
    "Nelas",
    "Senhorim",
    "União das freguesias de Carvalhal Redondo e Aguieira",
    "União das freguesias de Santar e Moreira",
    "Vilar Seco",
  ],
  'Évora': [
    "Canaviais",
    "Nossa Senhora da Graça do Divor",
    "Nossa Senhora de Machede",
    "São Bento do Mato",
    "São Miguel de Machede",
    "Torre de Coelheiros",
    "União das freguesias de Bacelo e Senhora da Saúde",
    "União das freguesias de Malagueira e Horta das Figueiras",
    "União das freguesias de Nossa Senhora da Tourega e Nossa Senhora de Guadalupe",
    "União das freguesias de São Manços e São Vicente do Pigeiro",
    "União das freguesias de São Sebastião da Giesteira e Nossa Senhora da Boa Fé",
    "União das freguesias de Évora (São Mamede, Sé, São Pedro e Santo Antão)",
  ],
  'Murça': [
    "Candedo",
    "Fiolhoso",
    "Jou",
    "Murça",
    "União das freguesias de Carva e Vilares",
    "União das freguesias de Noura e Palheiros",
    "Valongo de Milhais",
  ],
  'Tábua': [
    "Candosa",
    "Carapinha",
    "Midões",
    "Mouronho",
    "Póvoa de Midões",
    "São João da Boa Vista",
    "Tábua",
    "União das freguesias de Covas e Vila Nova de Oliveirinha",
    "União das freguesias de Espariz e Sinde",
    "União das freguesias de Pinheiro de Coja e Meda de Mouros",
    "União das freguesias de Ázere e Covelo",
  ],
  'Peso da Régua': [
    "Canelas",
    "Fontelas",
    "Loureiro",
    "Poiares",
    "Sedielos",
    "União das freguesias de Galafura e Covelinhas",
    "União das freguesias de Moura Morta e Vinhós",
    "União das freguesias de Peso da Régua e Godim",
    "Vilarinho dos Freires",
  ],
  'Montijo': [
    "Canha",
    "Sarilhos Grandes",
    "União das freguesias de Atalaia e Alto Estanqueiro-Jardia",
    "União das freguesias de Montijo e Afonsoeiro",
    "União das freguesias de Pegões",
  ],
  'Ponta do Sol': [
    "Canhas",
    "Madalena do Mar",
    "Ponta do Sol",
  ],
  'Machico': [
    "Caniçal",
    "Machico",
    "Porto da Cruz",
    "Santo António da Serra",
    "Água de Pena",
  ],
  'Sousel': [
    "Cano",
    "Casa Branca",
    "Santo Amaro",
    "Sousel",
  ],
  'Vieira do Minho': [
    "Cantelães",
    "Eira Vedra",
    "Guilhofrei",
    "Louredo",
    "Mosteiro",
    "Parada de Bouro",
    "Pinheiro",
    "Rossas",
    "Salamonde",
    "Tabuaças",
    "União das freguesias de Anissó e Soutelo",
    "União das freguesias de Anjos e Vilar do Chão",
    "União das freguesias de Caniçada e Soengas",
    "União das freguesias de Ruivães e Campos",
    "União das freguesias de Ventosa e Cova",
    "Vieira do Minho",
  ],
  'Alandroal': [
    "Capelins (Santo António)",
    "Santiago Maior",
    "Terena (São Pedro)",
    "União das freguesias de Alandroal (Nossa Senhora da Conceição), São Brás dos Matos (Mina do Bugalho) e Juromenha (Nossa Senhora do Loreto)",
  ],
  'Horta': [
    "Capelo",
    "Castelo Branco",
    "Cedros",
    "Feteira",
    "Flamengos",
    "Horta (Angústias)",
    "Horta (Conceição)",
    "Horta (Matriz)",
    "Pedro Miguel",
    "Praia do Almoxarife",
    "Praia do Norte",
    "Ribeirinha",
    "Salão",
  ],
  'Mira': [
    "Carapelhos",
    "Mira",
    "Praia de Mira",
    "Seixo",
  ],
  'Aguiar da Beira': [
    "Carapito",
    "Cortiçada",
    "Dornelas",
    "Eirado",
    "Forninhos",
    "Pena Verde",
    "Pinheiro",
    "União das freguesias de Aguiar da Beira e Coruche",
    "União das freguesias de Sequeiros e Gradiz",
    "União das freguesias de Souto de Aguiar da Beira e Valverde",
  ],
  'Alenquer': [
    "Carnota",
    "Meca",
    "Olhalvo",
    "Ota",
    "União das freguesias de Abrigada e Cabanas de Torres",
    "União das freguesias de Aldeia Galega da Merceana e Aldeia Gavinha",
    "União das freguesias de Alenquer (Santo Estêvão e Triana)",
    "União das freguesias de Carregado e Cadafais",
    "União das freguesias de Ribafria e Pereiro de Palhacana",
    "Ventosa",
    "Vila Verde dos Francos",
  ],
  'Carrazeda de Ansiães': [
    "Carrazeda de Ansiães",
    "Fonte Longa",
    "Linhares",
    "Marzagão",
    "Parambos",
    "Pereiros",
    "Pinhal do Norte",
    "Pombal",
    "Seixo de Ansiães",
    "União das freguesias de Amedo e Zedes",
    "União das freguesias de Belver e Mogo de Malta",
    "União das freguesias de Castanheiro do Norte e Ribalonga",
    "União das freguesias de Lavandeira, Beira Grande e Selores",
    "Vilarinho da Castanheira",
  ],
  'Oliveira de Azeméis': [
    "Carregosa",
    "Cesar",
    "Fajões",
    "Loureiro",
    "Macieira de Sarnes",
    "Nogueira do Cravo",
    "Ossela",
    "Pindelo",
    "São Martinho da Gândara",
    "São Roque",
    "União das freguesias de Oliveira de Azeméis, Santiago de Riba-Ul, Ul, Macinhata da Seixa e Madail",
    "União das freguesias de Pinheiro da Bemposta, Travanca e Palmaz",
    "Vila de Cucujães",
  ],
  'Chamusca': [
    "Carregueira",
    "Ulme",
    "União das freguesias da Chamusca e Pinheiro Grande",
    "União das freguesias de Parreira e Chouto",
    "Vale de Cavalos",
  ],
  'Bombarral': [
    "Carvalhal",
    "Pó",
    "Roliça",
    "União das freguesias do Bombarral e Vale Covo",
  ],
  'Penacova': [
    "Carvalho",
    "Figueira de Lorvão",
    "Lorvão",
    "Penacova",
    "Sazes do Lorvão",
    "União das freguesias de Friúmes e Paradela",
    "União das freguesias de Oliveira do Mondego e Travanca do Mondego",
    "União das freguesias de São Pedro de Alva e São Paio de Mondego",
  ],
  'Mafra': [
    "Carvoeira",
    "Encarnação",
    "Ericeira",
    "Mafra",
    "Milharado",
    "Santo Isidoro",
    "União das freguesias de Azueira e Sobral da Abelheira",
    "União das freguesias de Enxara do Bispo, Gradil e Vila Franca do Rosário",
    "União das freguesias de Igreja Nova e Cheleiros",
    "União das freguesias de Malveira e São Miguel de Alcainça",
    "União das freguesias de Venda do Pinheiro e Santo Estêvão das Galés",
  ],
  'São João da Pesqueira': [
    "Castanheiro do Sul",
    "Ervedosa do Douro",
    "Nagozelo do Douro",
    "Paredes da Beira",
    "Riodades",
    "Soutelo do Douro",
    "União das freguesias de São João da Pesqueira e Várzea de Trevões",
    "União das freguesias de Trevões e Espinhosa",
    "União das freguesias de Vilarouco e Pereiros",
    "Vale de Figueira",
    "Valongo dos Azeites",
  ],
  'Figueira de Castelo Rodrigo': [
    "Castelo Rodrigo",
    "Escalhão",
    "Figueira de Castelo Rodrigo",
    "Mata de Lobos",
    "União das freguesias de Algodres, Vale de Afonsinho e Vilar de Amargo",
    "União das freguesias de Almofala e Escarigo",
    "União das freguesias de Cinco Vilas e Reigada",
    "União das freguesias de Freixeda do Torrão, Quintã de Pêro Martins e Penha de Águia",
    "União das freguesias do Colmeal e Vilar Torpim",
    "Vermiosa",
  ],
  'Penalva do Castelo': [
    "Castelo de Penalva",
    "Esmolfe",
    "Germil",
    "Lusinde",
    "Pindo",
    "Real",
    "Sezures",
    "Trancozelos",
    "União das freguesias de Antas e Matela",
    "União das freguesias de Vila Cova do Covelo/Mareco",
    "Ínsua",
  ],
  'Maia': [
    "Castêlo da Maia",
    "Cidade da Maia",
    "Folgosa",
    "Milheirós",
    "Moreira",
    "Nogueira e Silva Escura",
    "Pedrouços",
    "São Pedro Fins",
    "Vila Nova da Telha",
    "Águas Santas",
  ],
  'Santa Cruz das Flores': [
    "Caveira",
    "Cedros",
    "Ponta Delgada",
    "Santa Cruz das Flores",
  ],
  'Sever do Vouga': [
    "Cedrim",
    "Couto de Esteves",
    "Dornelas",
    "Paradela",
    "Pessegueiro do Vouga",
    "Rocas do Vouga",
    "Sever do Vouga",
    "Silva Escura",
    "Talhadas",
  ],
  'Sabrosa': [
    "Celeirós",
    "Covas do Douro",
    "Gouvinhas",
    "Parada de Pinhão",
    "Paços",
    "Sabrosa",
    "Souto Maior",
    "São Lourenço de Ribapinhão",
    "Torre do Pinhão",
    "União das freguesias de Provesende, Gouvães do Douro e São Cristóvão do Douro",
    "União das freguesias de São Martinho de Antas e Paradela de Guiães",
    "Vilarinho de São Romão",
  ],
  'Mortágua': [
    "Cercosa",
    "Espinho",
    "Marmeleira",
    "Pala",
    "Sobral",
    "Trezói",
    "União das freguesias de Mortágua, Vale de Remígio, Cortegaça e Almaça",
  ],
  'Faro': [
    "Conceição",
    "Estoi",
    "Montenegro",
    "Santa Bárbara de Nexe",
    "União das freguesias de Faro (Sé e São Pedro)",
  ],
  'Constância': [
    "Constância",
    "Montalvo",
    "Santa Margarida da Coutada",
  ],
  'Vila Nova de Cerveira': [
    "Cornes",
    "Covas",
    "Gondarém",
    "Loivo",
    "Mentrestido",
    "Sapardos",
    "Sopo",
    "União das freguesias de Campos e Vila Meã",
    "União das freguesias de Candemil e Gondar",
    "União das freguesias de Reboreda e Nogueira",
    "União das freguesias de Vila Nova de Cerveira e Lovelhe",
  ],
  'Reguengos de Monsaraz': [
    "Corval",
    "Monsaraz",
    "Reguengos de Monsaraz",
    "União das freguesias de Campo e Campinho",
  ],
  'Corvo': [
    "Corvo",
  ],
  'Almada': [
    "Costa da Caparica",
    "União das freguesias de Almada, Cova da Piedade, Pragal e Cacilhas",
    "União das freguesias de Caparica e Trafaria",
    "União das freguesias de Charneca de Caparica e Sobreda",
    "União das freguesias de Laranjeiro e Feijó",
  ],
  'Póvoa de Lanhoso': [
    "Covelas",
    "Ferreiros",
    "Galegos",
    "Garfe",
    "Geraz do Minho",
    "Lanhoso",
    "Monsul",
    "Póvoa de Lanhoso (Nossa Senhora do Amparo)",
    "Rendufinho",
    "Santo Emilião",
    "Serzedelo",
    "Sobradelo da Goma",
    "São João de Rei",
    "Taíde",
    "Travassos",
    "União das freguesias de Calvos e Frades",
    "União das freguesias de Campos e Louredo",
    "União das freguesias de Esperança e Brunhais",
    "União das freguesias de Fonte Arcada e Oliveira",
    "União das freguesias de Verim, Friande e Ajude",
    "União das freguesias de Águas Santas e Moure",
    "Vilela",
  ],
  'Cuba': [
    "Cuba",
    "Faro do Alentejo",
    "Vila Alva",
    "Vila Ruiva",
  ],
  'Penela': [
    "Cumeeira",
    "Espinhal",
    "Podentes",
    "União das freguesias de São Miguel, Santa Eufémia e Rabaçal",
  ],
  'Câmara de Lobos': [
    "Curral das Freiras",
    "Câmara de Lobos",
    "Estreito de Câmara de Lobos",
    "Jardim da Serra",
    "Quinta Grande",
  ],
  'Matosinhos': [
    "Custóias",
    "Guifões",
    "Lavra",
    "Leça da Palmeira",
    "Leça do Balio",
    "Matosinhos",
    "Perafita",
    "Santa Cruz do Bispo",
    "Senhora da Hora",
    "São Mamede de Infesta",
  ],
  'Miranda do Douro': [
    "Duas Igrejas",
    "Genísio",
    "Malhadas",
    "Miranda do Douro",
    "Palaçoulo",
    "Picote",
    "Póvoa",
    "São Martinho de Angueira",
    "União das freguesias de Constantim e Cicouro",
    "União das freguesias de Ifanes e Paradela",
    "União das freguesias de Sendim e Atenor",
    "União das freguesias de Silva e Águas Vivas",
    "Vila Chã de Braciosa",
  ],
  'Tarouca': [
    "Dálvares",
    "Gouviães",
    "Mondim da Beira",
    "Salzedas",
    "São João de Tarouca",
    "Tarouca",
    "Ucanha",
    "União das freguesias de Granja Nova e Vila Chã da Beira",
    "Várzea da Serra",
  ],
  'Castro Verde': [
    "Entradas",
    "Santa Bárbara de Padrões",
    "São Marcos da Ataboeira",
    "União das freguesias de Castro Verde e Casével",
  ],
  'Povoação': [
    "Faial da Terra",
    "Furnas",
    "Nossa Senhora dos Remédios",
    "Povoação",
    "Ribeira Quente",
    "Água Retorta",
  ],
  'Lajes das Flores': [
    "Fajã Grande",
    "Fajãzinha",
    "Fazenda",
    "Lajedo",
    "Lajes das Flores",
    "Lomba",
    "Mosteiro",
  ],
  'Nazaré': [
    "Famalicão",
    "Nazaré",
    "Valado dos Frades",
  ],
  'Lagoa': [
    "Ferragudo",
    "Porches",
    "União das freguesias de Estômbar e Parchal",
    "União das freguesias de Lagoa e Carvoeiro",
  ],
  'Ponte de Sor': [
    "Foros de Arrão",
    "Galveias",
    "Longomel",
    "Montargil",
    "Ponte de Sor",
    "Tramaga",
    "Vale de Açor",
  ],
  'Salvaterra de Magos': [
    "Foros de Salvaterra",
    "Glória do Ribatejo",
    "Granho",
    "Marinhais",
    "Muge",
    "Salvaterra de Magos",
  ],
  'Vila Velha de Ródão': [
    "Fratel",
    "Perais",
    "Sarnadas de Ródão",
    "Vila Velha de Ródão",
  ],
  'Funchal': [
    "Funchal (Santa Luzia)",
    "Funchal (Santa Maria Maior)",
    "Funchal (São Pedro)",
    "Funchal (Sé)",
    "Imaculado Coração de Maria",
    "Monte",
    "Santo António",
    "São Gonçalo",
    "São Martinho",
    "São Roque",
  ],
  'Vila de Rei': [
    "Fundada",
    "São João do Peso",
    "Vila de Rei",
  ],
  'Olhão': [
    "Fuseta",
    "Moncarapacho",
    "Olhão",
    "Pechão",
    "Quelfes",
  ],
  'Ílhavo': [
    "Gafanha da Encarnação",
    "Gafanha da Nazaré",
    "Gafanha do Carmo",
    "Ílhavo (São Salvador)",
  ],
  'Ourique': [
    "Garvão",
    "Ourique",
    "Santa Luzia",
    "Santana da Serra",
    "União das freguesias de Panoias e Conceição",
  ],
  'Alcoutim': [
    "Giões",
    "Martim Longo",
    "União das freguesias de Alcoutim e Pereiro",
    "Vaqueiros",
  ],
  'Mourão': [
    "Granja",
    "Luz",
    "Mourão",
  ],
  'Pedrógão Grande': [
    "Graça",
    "Pedrógão Grande",
    "Vila Facaia",
  ],
  'Santa Cruz da Graciosa': [
    "Guadalupe",
    "Luz",
    "Santa Cruz da Graciosa",
    "São Mateus",
  ],
  'Setúbal': [
    "Gâmbia-Pontes-Alto da Guerra",
    "Sado",
    "Setúbal (São Sebastião)",
    "União das freguesias de Azeitão (São Lourenço e São Simão)",
    "União das freguesias de Setúbal (São Julião, Nossa Senhora da Anunciada e Santa Maria da Graça)",
  ],
  'Lousã': [
    "Gândaras",
    "Lousã",
    "Serpins",
    "União das freguesias de Foz de Arouce e Casal de Ermio",
    "Vilarinho",
  ],
  'Vizela': [
    "Infias",
    "Santa Eulália",
    "Tagilde",
    "União das freguesias de Caldas de Vizela (São Miguel e São João)",
    "Vizela (Santo Adrião)",
    "Vizela (São Paio)",
  ],
  'Miranda do Corvo': [
    "Lamas",
    "Miranda do Corvo",
    "União das freguesias de Semide e Rio Vide",
    "Vila Nova",
  ],
  'Vendas Novas': [
    "Landeira",
    "Vendas Novas",
  ],
  'Freixo de Espada à Cinta': [
    "Ligares",
    "Poiares",
    "União das freguesias de Freixo de Espada à Cinta e Mazouco",
    "União das freguesias de Lagoaça e Fornos",
  ],
  'Velas': [
    "Manadas (Santa Bárbara)",
    "Norte Grande (Neves)",
    "Rosais",
    "Santo Amaro",
    "Urzelina (São Mateus)",
    "Velas (São Jorge)",
  ],
  'Manteigas': [
    "Manteigas (Santa Maria)",
    "Manteigas (São Pedro)",
    "Sameiro",
    "Vale de Amoreira",
  ],
  'Marinha Grande': [
    "Marinha Grande",
    "Moita",
    "Vieira de Leiria",
  ],
  'Vila Real de Santo António': [
    "Monte Gordo",
    "Vila Nova de Cacela",
    "Vila Real de Santo António",
  ],
  'Proença-a-Nova': [
    "Montes da Senhora",
    "São Pedro do Esteval",
    "União das freguesias de Proença-a-Nova e Peral",
    "União das freguesias de Sobreira Formosa e Alvito da Beira",
  ],
  'Redondo': [
    "Montoito",
    "Redondo",
  ],
  'Campo Maior': [
    "Nossa Senhora da Expectação",
    "Nossa Senhora da Graça dos Degolados",
    "São João Baptista",
  ],
  'Castelo de Vide': [
    "Nossa Senhora da Graça de Póvoa e Meadas",
    "Santa Maria da Devesa",
    "Santiago Maior",
    "São João Baptista",
  ],
  'Entroncamento': [
    "Nossa Senhora de Fátima",
    "São João Baptista",
  ],
  'Odivelas': [
    "Odivelas",
    "União das freguesias de Pontinha e Famões",
    "União das freguesias de Póvoa de Santo Adrião e Olival Basto",
    "União das freguesias de Ramada e Caneças",
  ],
  'Oliveira do Bairro': [
    "Oiã",
    "Oliveira do Bairro",
    "Palhaça",
    "União das freguesias de Bustos, Troviscal e Mamarrosa",
  ],
  'Palmela': [
    "Palmela",
    "Pinhal Novo",
    "Quinta do Anjo",
    "União das freguesias de Poceirão e Marateca",
  ],
  'Vidigueira': [
    "Pedrógão",
    "Selmes",
    "Vidigueira",
    "Vila de Frades",
  ],
  'Vila Nova de Paiva': [
    "Pendilhe",
    "Queiriga",
    "Touro",
    "União das freguesias de Vila Nova de Paiva, Alhais e Fráguas",
    "Vila Cova à Coelheira",
  ],
  'Santa Comba Dão': [
    "Pinheiro de Ázere",
    "São Joaninho",
    "São João de Areias",
    "União das freguesias de Ovoa e Vimieiro",
    "União das freguesias de Santa Comba Dão e Couto do Mosteiro",
    "União das freguesias de Treixedo e Nagozela",
  ],
  'Vila Franca do Campo': [
    "Ponta Garça",
    "Ribeira Seca",
    "Ribeira das Tainhas",
    "Vila Franca do Campo (São Miguel)",
    "Vila Franca do Campo (São Pedro)",
    "Água de Alto",
  ],
  'Cartaxo': [
    "Pontével",
    "União das freguesias de Ereira e Lapa",
    "União das freguesias do Cartaxo e Vale da Pinta",
    "Valada",
    "Vale da Pedra",
    "Vila Chã de Ourique",
  ],
  'Sines': [
    "Porto Covo",
    "Sines",
  ],
  'Porto Santo': [
    "Porto Santo",
  ],
  'São Roque do Pico': [
    "Prainha",
    "Santa Luzia",
    "Santo Amaro",
    "Santo António",
    "São Roque do Pico",
  ],
  'Sesimbra': [
    "Quinta do Conde",
    "Sesimbra (Castelo)",
    "Sesimbra (Santiago)",
  ],
  'Barreiro': [
    "Santo António da Charneca",
    "União das freguesias de Alto do Seixalinho, Santo André e Verderena",
    "União das freguesias de Barreiro e Lavradio",
    "União das freguesias de Palhais e Coina",
  ],
  'Sobral de Monte Agraço': [
    "Santo Quintino",
    "Sapataria",
    "Sobral de Monte Agraço",
  ],
  'São Brás de Alportel': [
    "São Brás de Alportel",
  ],
  'São João da Madeira': [
    "São João da Madeira",
  ],
  'Vila Franca de Xira': [
    "União das freguesias de Alhandra, São João dos Montes e Calhandriz",
    "União das freguesias de Alverca do Ribatejo e Sobralinho",
    "União das freguesias de Castanheira do Ribatejo e Cachoeiras",
    "União das freguesias de Póvoa de Santa Iria e Forte da Casa",
    "Vialonga",
    "Vila Franca de Xira",
  ],
  'Castanheira de Pêra': [
    "União das freguesias de Castanheira de Pêra e Coentral",
  ],
};
