export const MUNICIPIOS = [
  "Amarante",
  "Baião",
  "Castelo de Paiva",
  "Celorico de Basto",
  "Cinfães",
  "Felgueiras",
  "Lousada",
  "Marco de Canaveses",
  "Paços de Ferreira",
  "Penafiel",
  "Resende",
  "Abrantes",
  "Águeda",
  "Aguiar da Beira",
  "Alandroal",
  "Albergaria-a-Velha",
  "Albufeira",
  "Alcácer do Sal",
  "Alcanena",
  "Alcobaça",
  "Alcochete",
  "Alcoutim",
  "Alenquer",
  "Alfândega da Fé",
  "Alijó",
  "Aljezur",
  "Aljustrel",
  "Almada",
  "Almeida",
  "Almeirim",
  "Almodôvar",
  "Alpiarça",
  "Alter do Chão",
  "Alvaiázere",
  "Alvito",
  "Amadora",
  "Amares",
  "Anadia",
  "Angra do Heroísmo",
  "Ansião",
  "Arcos de Valdevez",
  "Arganil",
  "Armamar",
  "Arouca",
  "Arraiolos",
  "Arronches",
  "Arruda dos Vinhos",
  "Aveiro",
  "Avis",
  "Azambuja",
  "Barcelos",
  "Barrancos",
  "Barreiro",
  "Batalha",
  "Beja",
  "Belmonte",
  "Benavente",
  "Bombarral",
  "Borba",
  "Boticas",
  "Braga",
  "Bragança",
  "Cabeceiras de Basto",
  "Cadaval",
  "Caldas da Rainha",
  "Calheta de São Jorge",
  "Calheta",
  "Câmara de Lobos",
  "Caminha",
  "Campo Maior",
  "Cantanhede",
  "Carrazeda de Ansiães",
  "Carregal do Sal",
  "Cartaxo",
  "Cascais",
  "Castanheira de Pêra",
  "Castelo Branco",
  "Castelo de Vide",
  "Castro Daire",
  "Castro Marim",
  "Castro Verde",
  "Celorico da Beira",
  "Chamusca",
  "Chaves",
  "Coimbra",
  "Condeixa-a-Nova",
  "Constância",
  "Coruche",
  "Corvo",
  "Covilhã",
  "Crato",
  "Cuba",
  "Elvas",
  "Entroncamento",
  "Espinho",
  "Esposende",
  "Estarreja",
  "Estremoz",
  "Évora",
  "Fafe",
  "Faro",
  "Ferreira do Alentejo",
  "Ferreira do Zêzere",
  "Figueira da Foz",
  "Figueira de Castelo Rodrigo",
  "Figueiró dos Vinhos",
  "Fornos de Algodres",
  "Freixo de Espada à Cinta",
  "Fronteira",
  "Funchal",
  "Fundão",
  "Gavião",
  "Góis",
  "Golegã",
  "Gondomar",
  "Gouveia",
  "Grândola",
  "Guarda",
  "Guimarães",
  "Horta",
  "Idanha-a-Nova",
  "Ílhavo",
  "Lagoa (Açores)",
  "Lagoa",
  "Lagos",
  "Lajes das Flores",
  "Lajes do Pico",
  "Lamego",
  "Leiria",
  "Lisboa",
  "Loulé",
  "Loures",
  "Lourinhã",
  "Lousã",
  "Mação",
  "Macedo de Cavaleiros",
  "Machico",
  "Madalena",
  "Mafra",
  "Maia",
  "Mangualde",
  "Manteigas",
  "Marinha Grande",
  "Marvão",
  "Matosinhos",
  "Mealhada",
  "Mêda",
  "Melgaço",
  "Mértola",
  "Mesão Frio",
  "Mira",
  "Miranda do Corvo",
  "Miranda do Douro",
  "Mirandela",
  "Mogadouro",
  "Moimenta da Beira",
  "Moita",
  "Monção",
  "Monchique",
  "Mondim de Basto",
  "Monforte",
  "Montalegre",
  "Montemor-o-Novo",
  "Montemor-o-Velho",
  "Montijo",
  "Mora",
  "Mortágua",
  "Moura",
  "Mourão",
  "Murça",
  "Murtosa",
  "Nazaré",
  "Nelas",
  "Nisa",
  "Nordeste",
  "Óbidos",
  "Odemira",
  "Odivelas",
  "Oeiras",
  "Oleiros",
  "Olhão",
  "Oliveira de Azeméis",
  "Oliveira de Frades",
  "Oliveira do Bairro",
  "Oliveira do Hospital",
  "Ourém",
  "Ourique",
  "Ovar",
  "Palmela",
  "Pampilhosa da Serra",
  "Paredes de Coura",
  "Paredes",
  "Pedrógão Grande",
  "Penacova",
  "Penalva do Castelo",
  "Penamacor",
  "Penedono",
  "Penela",
  "Peniche",
  "Peso da Régua",
  "Pinhel",
  "Pombal",
  "Ponta Delgada",
  "Ponta do Sol",
  "Ponte da Barca",
  "Ponte de Lima",
  "Ponte de Sor",
  "Portalegre",
  "Portel",
  "Portimão",
  "Porto de Mós",
  "Porto Moniz",
  "Porto Santo",
  "Porto",
  "Póvoa de Lanhoso",
  "Póvoa de Varzim",
  "Povoação",
  "Praia da Vitória",
  "Proença-a-Nova",
  "Redondo",
  "Reguengos de Monsaraz",
  "Ribeira Brava",
  "Ribeira de Pena",
  "Ribeira Grande",
  "Rio Maior",
  "Sabrosa",
  "Sabugal",
  "Salvaterra de Magos",
  "Santa Comba Dão",
  "Santa Cruz da Graciosa",
  "Santa Cruz das Flores",
  "Santa Cruz",
  "Santa Maria da Feira",
  "Santa Marta de Penaguião",
  "Santana",
  "Santarém",
  "Santiago do Cacém",
  "Santo Tirso",
  "São Brás de Alportel",
  "São João da Madeira",
  "São João da Pesqueira",
  "São Pedro do Sul",
  "São Roque do Pico",
  "São Vicente",
  "Sardoal",
  "Sátão",
  "Seia",
  "Seixal",
  "Sernancelhe",
  "Serpa",
  "Sertã",
  "Sesimbra",
  "Setúbal",
  "Sever do Vouga",
  "Silves",
  "Sines",
  "Sintra",
  "Sobral de Monte Agraço",
  "Soure",
  "Sousel",
  "Tábua",
  "Tabuaço",
  "Tarouca",
  "Tavira",
  "Terras de Bouro",
  "Tomar",
  "Tondela",
  "Torre de Moncorvo",
  "Torres Novas",
  "Torres Vedras",
  "Trancoso",
  "Trofa",
  "Vagos",
  "Vale de Cambra",
  "Valença",
  "Valongo",
  "Valpaços",
  "Velas",
  "Vendas Novas",
  "Viana do Alentejo",
  "Viana do Castelo",
  "Vidigueira",
  "Vieira do Minho",
  "Vila de Rei",
  "Vila do Bispo",
  "Vila do Conde",
  "Vila do Porto",
  "Vila Flor",
  "Vila Franca de Xira",
  "Vila Franca do Campo",
  "Vila Nova da Barquinha",
  "Vila Nova de Cerveira",
  "Vila Nova de Famalicão",
  "Vila Nova de Foz Côa",
  "Vila Nova de Gaia",
  "Vila Nova de Paiva",
  "Vila Nova de Poiares",
  "Vila Pouca de Aguiar",
  "Vila Real de Santo António",
  "Vila Real",
  "Vila Velha de Ródão",
  "Vila Verde",
  "Vila Viçosa",
  "Vimioso",
  "Vinhais",
  "Viseu",
  "Vizela",
  "Vouzela",
];
